TheThingsIndustries/lorawan-stack-docs

.hooks/install-hooks.go, .hooks/run-hooks.go, Makefile, README.md, go.mod, go.sum
Add git hooks to check commit messages, and instructions for initializing them
=> util: Add git hooks

doc/content/reference/configuration/console.md
Add gcs endpoint conf from https://github.com/TheThingsNetwork/lorawan-stack/pull/3176/
=> doc: Add console gcs config

doc/content/gateways/lora-basics-station/cups.md
Mistake in shortcode caused ref to render incorrect link - see https://thethingsstack.io/gateways/lora-basics-station/cups/#cups-server-certificate--cups-trust
=> doc: Fix cups certificate ref

doc/content/getting-started/aws/ecs/deployment/_index.md
Refers https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/236
- Add CW alarms doc
=> Add AWS CloudWatch alarm details

doc/content/reference/configuration/identity-server.md
Refs https://github.com/TheThingsNetwork/lorawan-stack/pull/3288
- Add IS key option
=> Add IS key encryption option

doc/data/glossary.yml
=> doc: Add keys to glossary

CONTRIBUTING.md, doc/content/example-template/_index.md
Add line break style guidelines
=> util: Add line break style guidelines

doc/content/getting-started/migrating-from-v2/mqtt-api-comparison.md
=> doc: Replace doc link with ref

doc/content/integrations/webhooks/webhook-templates/format.md
Added in https://github.com/TheThingsNetwork/lorawan-stack/pull/3419, landing in 3.10.0.
- Added field
=> Add new webhook template field

doc/content/integrations/aws-iot/_index.md, doc/content/integrations/aws-iot/default/_index.md, doc/content/integrations/aws-iot/default/messages.md, doc/content/integrations/mqtt/_index.md
Fix distributions for AWS IoT integration
Clarified the distributions as front matter and inline
=> AWS IoT Integration distributions

doc/content/getting-started/aws/_index.md, doc/content/getting-started/aws/ami/_index.md, doc/content/getting-started/aws/ecs/_index.md, doc/content/getting-started/aws/ecs/deployment/_index.md, doc/content/getting-started/aws/ecs/monitoring/_index.md, doc/content/reference/telemetry/_index.md
This PR adds documentation for the telemetry exported by The Things Stack, and documents monitoring the AWS ECS deployment.
Refs https://github.com/TheThingsIndustries/lorawan-stack/issues/2187
- Some housekeeping
- Document The Things Stack telemetry
- Document monitoring in AWS ECS deployments
=> Document Telemetry

CONTRIBUTING.md, doc/archetypes/section-bundle/troubleshooting.md, doc/content/gateways/kerlinkwirnetstation/_index.md, doc/content/gateways/lora-basics-station/troubleshooting.md, doc/content/getting-started/aws/ami/troubleshooting/_index.md, doc/content/getting-started/installation/troubleshooting.md, doc/content/integrations/aws-iot/default/troubleshooting.md
Rename troubleshooting sections for better search indexing. 
Also add a note to CONTRIBUTING and an example in the new section template.
=> doc: Rename troubleshooting sections

doc/content/getting-started/aws/ecs/deployment/_index.md
Add gateway secrets encryption key description. Refs https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/266
- Add gateway secrets encryption key description
=> Add gateway secrets encryption key description

doc/content/getting-started/troubleshooting/_index.md
Looks like a somehow deleted the troubleshooting section when I merged TTES + TTS :/ I don't see any other deletions in the merged branch so I think we're okay ->  https://github.com/TheThingsIndustries/lorawan-stack/compare/feature/doc-distribution
=> doc: Add troubleshooting

doc/content/devices/adding-devices/troubleshooting.md, doc/content/gateways/adding-gateways/troubleshooting.md, doc/content/getting-started/troubleshooting/_index.md
Rename for troubleshooting section that was merged after the last renaming PR
=> doc: Rename troubleshooting (again)

doc/content/integrations/adding-applications/_index.md
=> doc: Fix double sentences

doc/content/getting-started/aws/ecs/deployment/_index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/running-the-stack.md, doc/content/integrations/storage/_index.md, doc/content/integrations/storage/configuration.md, doc/content/integrations/storage/enable.md, doc/content/integrations/storage/retrieve.md, doc/content/reference/api/storage_integration.md, doc/content/reference/configuration/application-server.md, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml
References https://github.com/TheThingsIndustries/lorawan-stack/pull/2295
- Add `Storage Integration` section under Integrations
- Add Storage Integration API reference
Wait until https://github.com/TheThingsIndustries/lorawan-stack/pull/2295 is merged, and possibly until API is open-sourced.
=> doc: Storage Integration

doc/content/getting-started/migrating-from-networks/device-json.md
Closes #29
- Add proper examples for OTAA devices and OTAA devices with existing sessions
- Improve field descriptions, add links for values of enum fields.
- Specify which fields are required and under which conditions.
- Add example value for each field
Most of the changes are based on customer feedback.
=> doc: Update documentation for device JSON objects

doc/content/getting-started/installation/configuration/docker-compose-enterprise.yml, doc/content/getting-started/installation/configuration/docker-compose-open-source.yml
References https://github.com/TheThingsNetwork/lorawan-stack/issues/3465
- Update command for CockroachDB container
=> Update CockroachDB command in Getting Started guide

CODEOWNERS, doc/content/integrations/payload-formatters/javascript.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/74
=> Update ES5 description

doc/content/getting-started/installation/configuration/_index.md
Add note to make it clear that all installation configuration options are contained in the example files. Also clean up merge conflict relics
=> doc: Add installation notes

doc/content/getting-started/installation/configuration/_index.md, doc/content/getting-started/installation/running-the-stack.md, doc/content/getting-started/installation/troubleshooting.md
Add instructions for running docker-compose on `localhost`
=> Add localhost installation instructions

doc/content/reference/configuration/application-server.md
Documentation followup for https://github.com/TheThingsNetwork/lorawan-stack/pull/3293.
- Add documentation for the end device fetcher cache options
Will only be merged after https://github.com/TheThingsNetwork/lorawan-stack/pull/3293.
=> doc: Add AS end device fetcher cache configuration

doc/content/gateways/semtech-udp-packet-forwarder/_index.md
Add note that download is broken in 3.10.0
=> doc: Add global_conf bug note

doc/content/gateways/kerlinkwirnetistation/_index.md, doc/content/gateways/kerlinkwirnetstation/_index.md, doc/themes/the-things-stack/assets/css/theme.scss
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/72
Before, on small screens, content was cut off:
Now it's possible to horizontally scroll:
=> Add x overflow to content css

doc/content/gateways/tektelickonamicro/_index.md
=> doc: Update Kona Micro documentation link

doc/content/gateways/lora-basics-station/_index.md, doc/content/gateways/lora-basics-station/cups.md, doc/content/gateways/lora-basics-station/lns.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/188
- Add supported LBS authentication modes
- Add note that CUPS configures LNS
=> doc: Add lbs auth note

doc/content/integrations/payload-formatters/javascript.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/196
- Add note that v2 payload formatters work in v3
=> doc: Add v2 payload formatter note

doc/content/gateways/lora-basics-station/cups.md, doc/content/gateways/lora-basics-station/lns.md
Add instructions for correctly connecting to CUPS. 
Also some readability improvements.
=> doc: Add CUPS instructions

doc/content/devices/device-claiming/_index.md, doc/content/devices/device-claiming/claim-devices.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/60
=> doc: Add device claiming security session note

doc/content/reference/api/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/183
- Add note that v2 API is not v3 API.
=> doc: Add V2 API note

doc/content/getting-started/migrating/migrating-from-v2.md
On request of customers [link](https://github.com/TheThingsIndustries/lorawan-stack-support/issues/169) addition info on ttnctl infiguration is added. 
- Info in configuring the V2 ttnctl
=> doc: Update v2 migrations docs with info on CLI configuration

doc/content/getting-started/installation/running-the-stack.md
=> Remove trailing backslash

doc/content/integrations/storage/configuration.md
Add note that configuration is not necessary for Cloud
=> doc: Add cloud storage integration note

doc/content/getting-started/aws/_index.md, doc/content/getting-started/aws/ami/deployment-guide/_index.md, doc/content/getting-started/aws/ami/post-deployment/_index.md, doc/content/getting-started/aws/ami/troubleshooting/_index.md, doc/content/getting-started/aws/ecs/architecture/_index.md, doc/content/getting-started/aws/ecs/database-operations/_index.md, doc/content/getting-started/aws/ecs/deployment/_index.md, doc/content/getting-started/aws/ecs/prerequisites/_index.md
Just improving readability of AWS doc.
Reference #46
=> doc: Improving readability of AWS doc

doc/content/_index.html
Fix contributing link on homepage
=> doc: Fix contributing link

doc/content/reference/configuration/the-things-stack.md
This updates the configuration reference for changes made in https://github.com/TheThingsNetwork/lorawan-stack/pull/3535.
Refs https://github.com/TheThingsIndustries/lorawan-stack/issues/2426
=> Update configuration reference for trusted-proxies

doc/content/gateways/lora-basics-station/cups.md, doc/content/gateways/lora-basics-station/troubleshooting.md
Add correct rights to CUPS API key, some other minor cleanups
=> doc: Update CUPS API Key info

doc/content/getting-started/api/_index.md, doc/content/reference/api/_index.md, doc/content/reference/api/field-mask.md
Add some more `curl` http examples
=> doc: Add api curl examples

doc/content/integrations/cloud-integrations/thingspeak/_index.md, doc/content/integrations/cloud-integrations/thingspeak/thingspeak-setup/_index.md, doc/content/integrations/cloud-integrations/thingspeak/tts-setup/_index.md
Updating ThingSpeak integration doc to meet feedback.
Rewording, adding an example for uplink payload formatter, adjusting images.
TODO: Adjusting images depends on #126 review.
=> doc: Update ThingSpeak guide

doc/content/getting-started/installation/configuration/docker-compose-enterprise.yml, doc/content/getting-started/installation/configuration/docker-compose-open-source.yml
All of the rest of our configuration examples use Let's Encrypt by default, so let's also mount the acme dir by default
=> doc: Uncomment lets encrypt from docker-compose.yml

.github/workflows/pull_request.yml, .github/workflows/release.yml, Makefile
This PR hopefully improves caching between CI builds, so that they finish faster.
=> Improve caching in CI builds

doc/content/getting-started/installation/running-the-stack.md
Add note to enable OAuth client beyond tenant scope
=> doc: Add multi-tenant OAuth note

doc/content/getting-started/installation/certificates.md, doc/content/getting-started/installation/configuration/_index.md
Add a note to specify custom certificates in configuration files if using them, re: https://www.thethingsnetwork.org/forum/t/thethingsstack-v3-8-7-with-self-signed-certificate-forbidden-token-exchange-refused/38902/26
=> doc: Add localhost certificates note

.github/workflows/pull_request.yml, .github/workflows/release.yml
Fix base url in github actions
Fix base url in github actions
=> util: Fix base url

doc/content/integrations/storage/retrieve.md
Refs https://github.com/TheThingsNetwork/lorawan-stack/issues/3584
- Small fix to the time format
=> Fix time format in storage integration reference

doc/data/glossary.yml
Fix typo in Device ID entry in glossary
- [] Run Locally: Verified that the docs build using `make server`
=> doc: Fix typo in glossary

doc/content/_index.html
Value proposition taken from https://discuss.thethingsindustries.com/t/what-is-our-value-proposition/357
=> doc: Add value proposition to docs homepage

doc/content/devices/claim-atecc608a/_index.md, doc/content/devices/device-claiming/_index.md, doc/content/devices/device-claiming/make-device-claimable.md, doc/content/devices/end-device-templates/converting.md, doc/content/devices/end-device-templates/mapping.md, doc/content/getting-started/cloud-hosted/tti-join-server/_index.md, doc/content/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted.md, doc/content/getting-started/cloud-hosted/tti-join-server/register-devices.md, doc/content/integrations/aws-iot/default/_index.md, doc/content/integrations/aws-iot/default/architecture.md, doc/content/integrations/aws-iot/default/deployment-guide.md
Rename Global Join Server to The Things Join Server
=> Rename Global Join Server to The Things Join Server

doc/content/integrations/payload-formatters/cayenne.md
Add Cayenne LPP sensor constants reference, explain how `decoded_payload` fields are produced from sensor types.
=> Extend Cayenne LPP example

doc/content/integrations/mqtt/_index.md, doc/content/integrations/mqtt/cloud-hosted.md
Add `/location/solved` to available MQTT topics.
Should this be labeled with `new in version` shortcode?
=> doc: Add location solved to available topics

doc/content/integrations/storage/retrieve.md
This Quickfix PR fixes the URL of the HTTP API for the Storage Integration.
=> Fix Storage Integration HTTP API URL

doc/content/getting-started/aws/_index.md, doc/content/integrations/adding-integrations/_index.md, doc/content/integrations/aws-iot/_index.md
- Cross-referencing AWS and AWS IoT guides
- Adding a reference to an example of the LoRa Cloud integration
=> doc: Cross-referencing integration guides

doc/content/getting-started/user-management/_index.md
=> doc: Document admin rights

doc/content/gateways/kerlinkwirnetistation/_index.md, doc/content/gateways/kerlinkwirnetstation/_index.md
Update wirnet provisioning script version
- Update wirnet provisioning script version
=> Update wirnet provisioning script version

doc/content/gateways/lora-basics-station/cups.md
https://github.com/TheThingsNetwork/lorawan-stack/issues/3426#issuecomment-747268294
=> doc: Add note that CUPS overrides LNS

doc/content/getting-started/what-is-tts/_index.md
We got feedback that TTS, TTI, TTN are confusing, so proposing this intro section
=> doc: Add what is TTS section

doc/content/getting-started/migrating/configure-mac-settings.md, doc/content/getting-started/migrating/major-changes.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/266
=> doc: Document Rx1Delay v2 difference

doc/content/getting-started/troubleshooting/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/265
- Add network error to troubleshooting
=> doc: Add network errors to troubleshooting

doc/content/getting-started/cli/installing-cli/_index.md
Someone left feedback asking what auto completion is for 🤷🏼‍♀️
=> doc: Explain auto completion

doc/content/getting-started/cloud-hosted/addresses.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/195
- Add note that IS is not available on ´nam1´ or ´au1´
=> doc: Add note that IS is eu1 only

doc/content/reference/branding/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/268
=> doc: Update console branding instructions for cloud

doc/content/reference/email-templates/available.md
This documents the new fields that were added to email templates in https://github.com/TheThingsNetwork/lorawan-stack/pull/3625.
I don't think it makes a lot of sense to add a "new in version xxx" here.
=> Add TTL and FormatTTL to email templates

doc/content/getting-started/what-is-tts/_index.md
=> doc: Fix a broken reference

doc/content/reference/configuration/identity-server.md
This documents the `is.admin-rights-all` config option added in https://github.com/TheThingsNetwork/lorawan-stack/pull/3621.
Blocked on release with the changes.
=> Document is.admin-rights.all config option

doc/content/gateways/lora-basics-station/cups.md, doc/content/getting-started/cli/installing-cli/_index.md, doc/content/integrations/storage/configuration.md, doc/content/integrations/storage/enable.md, doc/content/integrations/storage/retrieve.md
Some users encountered errors with CUPS and Storage Integration, probably because they were using outdated CLI. This PR adds notes to upgrade.
=> Add instructions to update CLI

doc/content/integrations/storage/retrieve.md
Document field mask paths for the Storage Integration API.
- Add field mask paths example
- Separate HTTP API and CLI examples
- Minor fixes
=> Improve Storage Integration API documentation

doc/content/download.html
Fix broken link to open source in downloads page
=> doc: Fix broken open source link

doc/content/getting-started/installation/certificates.md
=> doc: Remove duplicate custom certs section

doc/content/reference/email-templates/available.md
This updates the email template reference to include the variables updated in https://github.com/TheThingsNetwork/lorawan-stack/pull/3678.
This is blocked until https://github.com/TheThingsNetwork/lorawan-stack/pull/3678 is merged and v3.11 is released.
=> Update variables and functions in email templates

doc/config/_default/config.toml
=> doc: Update to 3.11

doc/data/api/tti.lorawan.v3/messages.yml, doc/data/api/tti.lorawan.v3/services.yml, doc/data/api/ttn.lorawan.v3/enums.yml, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml
This updates the API data from the v3.11 release
=> Update API data

doc/content/download.html
Remove table, update purchasing links, fix relative urls
=> doc: Update download page

CONTRIBUTING.md, doc/archetypes/section-bundle/_index.md, doc/content/getting-started/installation/configuration/_index.md, doc/content/getting-started/migrating/migrating-from-v2.md, doc/content/integrations/aws-iot/default/deployment-guide.md, doc/content/reference/branding/_index.md, doc/content/reference/configuration/console.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/configuration/network-server.md, doc/content/reference/configuration/the-things-stack.md, doc/content/reference/email-templates/available.md, doc/content/reference/networking/_index.md, doc/content/reference/telemetry/_index.md
Fixup for #134 , consolidate `distributions-inline` and `distributions` shortcodes
=> util: Replace distributions-inline with distributions shortcode

doc/content/devices/adding-devices/troubleshooting.md, doc/content/gateways/semtech-udp-packet-forwarder/_index.md, doc/content/gateways/semtech-udp-packet-forwarder/troubleshooting.md
Adding a troubleshooting section for UDP packet forwarder, with start on the failing downlinks. Also adding a short point on troubleshooting devices.
Ref: #208
@johanstokking sanity check please. I addressed only what was instructed at the moment, but with some guidance I can research and add more info. Also, I'm not sure how can a person change the device's link check behavior?
=> doc: Add troubleshooting for UDP packet forwarder and devices

doc/content/getting-started/aws/ecs/database-operations/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-aws/issues/229
- Add the `as-db` and `ns-db` commands to the CFN template documentation
=> Document the ns-db,as-db,dcs-db commands

.github/ISSUE_TEMPLATE/release.md
Create process for releases, migrated from https://github.com/TheThingsNetwork/lorawan-stack/pull/3783/files
- Add release template
=> Add release template

doc/content/integrations/aws-iot/default/things.md, doc/content/reference/id-eui-constraints/index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/211
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/267
- Document how TTS uses IDs and EUIs
=> Document ID and EUI constraints

doc/content/integrations/aws-iot/default/things.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/222
- Add note and link to device claiming
=> Explain creating vs claiming device in AWS IoT

doc/content/devices/class-b/index.md, doc/content/devices/class-c/_index.md, doc/content/devices/multicast/index.md, doc/content/reference/spec-regional-parameters/index.md
Closes #242 
Add sections for:
- Class B
- Supported Specifications and RPS
=> Add sections for supported classes, LoRaWAN specifications, and Regional Parameters

doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml, doc/data/ttn-lw-cli.yml
This updates the data files for the v3.11.2 release
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/253
Refs https://github.com/TheThingsNetwork/lorawan-stack/issues/3892
N/A
Updated API and CLI data.
=> Update data for v3.11.2 release

doc/assets/css/header/search.scss
Add a border to search as a temporary style fix
old search styling didn't work for new docs, replaced it:
old:
new:
@pierrephz , we'll need to do a bigger redesign on search. Maybe something like this:
=> doc: Search layout quickfix

doc/assets/css/common/variables.scss, doc/assets/css/header/nav.scss, doc/assets/js/theme.js
Fix for migration banner blocking top of docs
...
=> doc: Add banner html padding

doc/content/reference/packet-broker/enable.md
Add note re: https://discuss.thethingsindustries.com/t/peering-from-tti-cloud-to-ttn-v3/465/2
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/249
=> Add note about peering on TTS cloud

doc/content/getting-started/aws/ecs/monitoring/_index.md, doc/content/reference/telemetry/_index.md
This pull request adds descriptions for the PBA telemetry
Blocked on https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/380
=> Add PBA telemetry descriptions

doc/content/reference/components/device-claiming-server.md, doc/content/reference/configuration/device-claiming-server.md
Closes https://github.com/TheThingsIndustries/lorawan-stack/issues/2112
- Add DCS component info
- Extend DCS configuration a bit
=> Device Claiming Server documentation

doc/content/getting-started/aws/ecs/deployment/_index.md
Refs https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/373
NA
- Add GCS deployment description
=> Add GCS deployment description

doc/content/getting-started/installation/certificates.md, doc/content/getting-started/installation/configuration/docker-compose-custom-certificates.yml, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-custom-certificates.yml
=> doc: Add ACME localhost note and improve certs docs

doc/content/getting-started/upgrading/_index.md
Closes #232 
- Clean up `Upgrading The Things Stack` page.
- Add notes on backup and migrations.
=> Add backup notes

.github/ISSUE_TEMPLATE/release.md, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml, doc/data/ttn-lw-cli.yml
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/270
This is a checklist for releases. This is filled in by both the releaser and the reviewer where necessary.
```bash
$ tools/bin/mage ttiProto:hugoData
```
```bash
$ cp -r doc/data/api /path/to/lorawan-stack-docs/doc/data/
```
```bash
$ go build -tags tti ./cmd/tti-lw-cli
```
```bash
$ HOME=$HOME ./tti-lw-cli gen-yaml-doc -o /path/to/lorawan-stack-docs/doc/data/
```
```
```
```
doc/data/ttn-lw-cli.yml
```
- [ ] All generated documentation matches the version that is being …
=> Release 3.11.3

doc/content/devices/device-claiming/claim-devices.md, doc/content/devices/device-claiming/make-device-claimable.md, doc/content/gateways/gateway-claiming/_index.md, doc/content/gateways/gateway-claiming/claim-gateways.md, doc/content/gateways/gateway-claiming/make-gateways-claimable.md
Add gateway claiming doc; refs https://github.com/TheThingsIndustries/lorawan-stack/pull/2615
- Add gateway claiming doc
=> Add gateway claiming reference

doc/content/getting-started/installation/troubleshooting.md
Update troubleshooting with this error:
=> doc: Update troubleshooting

doc/content/reference/configuration/the-things-stack.md, doc/content/reference/rate-limiting/_index.md, doc/data/rate-limiting.yml, doc/layouts/shortcodes/rate-limiting.html
Configuration reference for https://github.com/TheThingsNetwork/lorawan-stack/pull/3920
Still draft so there may be changes until https://github.com/TheThingsNetwork/lorawan-stack/pull/3920 is merged, will update afterwards.
- Add reference for Rate Limiting configuration classes and keys
Needs to reflect any changes made until https://github.com/TheThingsNetwork/lorawan-stack/pull/3920 is merged.
=> Rate Limiting documentation reference

.github/ISSUE_TEMPLATE/release.md, doc/config/_default/config.toml, doc/content/reference/api/application.md, doc/content/reference/api/gateway.md, doc/content/reference/api/organization.md, doc/content/reference/api/user.md, doc/data/api/tti.lorawan.v3/messages.yml, doc/data/api/tti.lorawan.v3/services.yml, doc/data/api/ttn.lorawan.v3/enums.yml, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml, doc/data/ttn-lw-cli.yml
Updating data files for v3.12.0 release.
Closing #302 
Referencing [TheThingsNetwork/lorawan-stack#4022](https://github.com/TheThingsNetwork/lorawan-stack/pull/4022)
Updated API and CLI data.
I followed the steps from the release template. This is the first time I'm doing this and I see something isn't right, so please give me some instructions how to fix it.
PS: In my local environment, API documentation was not generated to `doc/data/api` folder, but the `api` folder. Also, file `doc/data/api/tti.lorawan.v3/enums.yml` is missing, while the template says it should be included.
=> doc: Update data for v3.12.0 release

doc/content/reference/rate-limiting/_index.md, doc/data/rate-limiting.yml
Follow up after changes applied in https://github.com/TheThingsNetwork/lorawan-stack/pull/4017
=> Quickfix rate limiting config

doc/content/getting-started/upgrading/_index.md
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/4047
- Remove `ttn-lw-stack dr-db migrate` step. There is no such command, and the device repository index is built as part of the Docker image.
=> Remove wrong ttn-lw-stack dr-db migrate upgrade step

doc/content/getting-started/migrating/migrating-from-v2.md
Quickfix PR, note that ttn-lw-migrate should be 0.5.0 or newer
This is temporary until #305 is merged.
=> Add temporary note for ttn-lw-migrate version 0.5.0

doc/content/reference/configuration/identity-server.md
This adds the configuration reference for https://github.com/TheThingsNetwork/lorawan-stack/pull/4039.
=> Add IS password rejection options to config reference

doc/content/getting-started/quick-start/index.md
This creates an actual quick start for using The Things Stack.
=> doc: Add quick start

doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/ttn-lw-cli.yml
This updates the docs for the v3.12.1 release.
Closes #309
=> Update for v3.12.1 release

doc/content/getting-started/aws/ecs/updating/_index.md
Closes #115 
Added section about updating ECS deployment
I was not sure what to write about, so requests to write more information about something are welcome.
=> doc: Add AWS ECS updating guide

doc/content/reference/packet-broker/configure/registration.md, doc/content/reference/packet-broker/configure/routing-policies.md, doc/layouts/shortcodes/cli-only.html
Closes #318
When `hint-upgrade` is set:
- Add `hint-upgrade` param to `cli-only`
- Fix `ttn-lw-cli packetbroker registration` command
- Small clarifications
=> Fix and clarify Packet Broker documentation

doc/content/getting-started/console/_index.md
Fix a link typo in Console page
- [] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
=> doc: Fix typo

doc/content/whats-new/3.12.2.md, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml, doc/data/ttn-lw-cli.yml
=> doc: Update data for v3.12.2 release

doc/assets/css/common/global.scss
Accidentally merged pr before incorporating review fixes, small style update to css
=> Update hash css

doc/content/getting-started/api/_index.md, doc/content/integrations/webhooks/scheduling-downlinks.md
Add API example for using the `decoded_payload` downlink field.
Closes #258 
...
=> Add API examples for downlink with payload encoder

doc/layouts/partials/distribution-icons.html
=> util: Fix broken downloads link

doc/content/gateways/nasysoutdoorgateway/_index.md
=> Fix typo in nasysoutdoorgateway

doc/content/whats-new/3.12.3.md, doc/data/api/ttn.lorawan.v3/enums.yml, doc/data/api/ttn.lorawan.v3/messages.yml
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/343
```
```
```
doc/data/ttn-lw-cli.yml
```
- [ ] All generated documentation matches the version that is being released.
=> Release v3.12.3

doc/assets/css/common/global.scss, doc/assets/css/header/nav.scss, doc/assets/js/theme.js, doc/layouts/_default/list.html, doc/layouts/_default/single.html, doc/layouts/partials/header-hash.html
Removed the partial hardcoding anchor hashes, and replaced it with JS, because the hashes were appearing in Algolia scrapes. Also cleaned up some js and the migration bar.
Search with hashes appearing (will be fixed after next scrape):
Migration bar before padding fix:
After fix:
=> Change anchor hashes to JS

doc/content/getting-started/cli/installing-cli/_index.md, doc/content/getting-started/cli/login/_index.md
=> Installation & configuration instructions for tti-lw-cli

doc/content/reference/configuration/application-server.md
Documentation for https://github.com/TheThingsNetwork/lorawan-stack/pull/4133
=> doc: Document `as.formatters.max-parameter-length` option

doc/config/_default/config.toml, doc/content/whats-new/3.13.0.md, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml, doc/data/ttn-lw-cli.yml
Closes #359 
```
```
```
doc/data/ttn-lw-cli.yml
```
=> doc: Release docs v3.13.0

doc/content/integrations/payload-formatters/device-repo.md
Add link to device repo on TTI website
=> doc: Update device repo links

doc/content/whats-new/3.13.1.md
Closing #376 
```
```
```
doc/data/ttn-lw-cli.yml
```
=> doc: Update docs for v3.13.1 release

doc/content/reference/data-formats/_index.md
References https://github.com/TheThingsNetwork/lorawan-stack/issues/4218
- Add example gateway location metadata in uplink message.
...
=> Add example gateway location uplink message metadata

CONTRIBUTING.md, doc/archetypes/section-bundle/_index.md, doc/assets/css/common/global.scss, doc/assets/css/sidebar/sidebar.scss, doc/content/getting-started/aws/ecs/deployment/_index.md, doc/content/getting-started/installation/configuration/index.md, doc/content/integrations/aws-iot/_index.md, doc/content/reference/configuration/application-server.md, doc/content/reference/configuration/console.md, doc/content/reference/configuration/device-claiming-server.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/configuration/network-server.md, doc/content/reference/configuration/packet-broker-agent.md, doc/content/reference/configuration/the-things-stack.md, doc/content/reference/telemetry/_index.md, doc/layouts/_default/list.html, doc/layouts/_default/single.html, doc/layouts/partials/deprecated-in-version.html, doc/layouts/partials/new-in-version.html, doc/layouts/partials/pages-cards.html, doc/layouts/partials/removed-in-version.html, doc/layouts/shortcodes/removed-in-version.html
Shortcodes in headings were breaking anchor links and causing headaches, so moving them to the first line of the next paragraph, like HUGO documentation does -> https://gohugo.io/variables/site/#get-the-site-object-from-a-partial
Closes #325
=> Move inline shortcodes to next line

doc/content/gateways/adding-gateways/troubleshooting.md
=> doc: Update gateway troubleshooting

doc/content/gateways/multitechconduit/lbs.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/401
- Added the `prerequisites` information in the current docs according to the Multitech reference. http://www.multitech.net/developer/software/lora/running-basic-station-on-conduit/
=> Add a prerequisites section to the Multitech Conduit AEP gateways doc for supporting LBS

doc/content/whats-new/3.13.2.md, doc/data/api/tti.lorawan.v3/messages.yml, doc/data/api/tti.lorawan.v3/services.yml, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/ttn-lw-cli.yml
=> doc: Update documentation for v3.13.2 release

doc/assets/js/theme.js
Activate tab if anchor link containing it is hidden. Also fixes bug where no tab is activated if localStorage contains a tabName that doesn't exist.
Closes #286 
- Activate tab if it contains clicked anchor link
- Fix bug where no tab is activated if localStorage contains a tabName that doesn't exist
=> Activate tabs with anchor links

doc/content/getting-started/migrating/device-json.md
=> Update Rx1 delay field name according to 3.12.0 API

doc/content/reference/adr/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/274
- Add ADR implementation reference
=> Add ADR implementation reference

doc/content/devices/adding-devices/_index.md, doc/content/gateways/adding-gateways/_index.md, doc/content/getting-started/events/_index.md, doc/content/getting-started/user-management/_index.md, doc/content/getting-started/user-management/org/_index.md, doc/content/getting-started/user-management/rights/_index.md, doc/content/getting-started/user-management/user/_index.md, doc/content/integrations/adding-applications/_index.md, doc/content/integrations/payload-formatters/_index.md, doc/content/integrations/webhooks/creating-webhooks.md
=> doc: Add videos

doc/assets/css/common/global.scss, doc/assets/css/common/variables.scss, doc/layouts/index.html, doc/layouts/partials/whats-new.html
Home page UI improvements
- Modified the blue color
- Increased width of title and subtitle sections
- Reworked the UI of the `what’s new` section
- Modified the sizing of the schema
- Changes cards UI of the front page
@benolayinka, the frontend of the `what’s new` section is done, but I haven’t managed to do the backend myself.
By that I mean:
- the data of the current version of the console (1)
- display real datas of the new features in the section (2)
- the real number of new features that have been added (3)
Ben, is it possible for you to use my branch to complete the backend, end push?
If there is any other question, you can message me
I haven't removed the old `what’s new` section (turned it into comment). Would like to have an approval before to remove it for good
- [ ] Run …
=> doc: Improve ui of the home page

doc/content/reference/id-eui-constraints/index.md
Documents https://github.com/TheThingsNetwork/lorawan-stack/issues/3723
=> Update ID constraints for shorter ID

doc/content/gateways/thethingsindoorgateway/_index.md
=> Add Claim Authentication Code Mismatch to TTIG FAQ

doc/content/whats-new/3.13.3.md, doc/data/api/ttn.lorawan.v3/enums.yml, doc/data/api/ttn.lorawan.v3/messages.yml, doc/data/api/ttn.lorawan.v3/services.yml, doc/data/ttn-lw-cli.yml
=> doc: v3.13.3 release docs

doc/content/getting-started/installation/troubleshooting.md
Extra reason for Token Exchange Refused.
I hit the Token Exchange Refused error when trying to login. The cause was not either of the two reasons already listed.
None.
One-liner.
It cost me more than an hour to figure this out. I want to save time for the next person.
=> doc: Troubleshooting - extra reason for Token Exchange Refused

doc/content/integrations/webhooks/_index.md, doc/content/integrations/webhooks/creating-webhooks.md, doc/content/integrations/webhooks/webhook-templates/format.md
- Clarify webhook docs
- Add use cases
- Add `service-data` template endpoint
=> Improve webhook docs

doc/content/getting-started/api/_index.md, doc/content/getting-started/aws/_index.md, doc/content/getting-started/cli/_index.md, doc/content/getting-started/cloud-hosted/_index.md, doc/content/getting-started/console/_index.md, doc/content/getting-started/events/_index.md, doc/content/getting-started/installation/_index.md, doc/content/getting-started/migrating/_index.md, doc/content/getting-started/troubleshooting/_index.md, doc/content/getting-started/ttn/_index.md, doc/content/getting-started/upgrading/_index.md, doc/content/getting-started/user-management/_index.md, doc/themes/the-things-stack/layouts/partials/pages-cards.html
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/73
- Remove unnecessary weights from getting-started
- Clarify deployment specific instructions
=> Reorder getting started

doc/data/glossary.yml
Add tenant ID to glossary, re: docs feedback widget
=> doc: Add tenant ID to glossary

doc/content/gateways/thethingsindoorgateway/_index.md
Remove remark on iot-shop.de
- Remove remark on iot-shop.de
=> Remove remark on iot-shop.de

doc/content/gateways/lora-basics-station/implementation-details.md, doc/content/reference/lbs-implementation-guide/implementation-details.md
Document DevEui field in LBS downlinks; Refs https://github.com/TheThingsNetwork/lorawan-stack/issues/4085
- Document DevEui field in LBS downlinks
=> Document DevEui field in LBS downlinks

doc/content/reference/api/application.md, doc/content/reference/api/application_pub_sub.md, doc/content/reference/api/application_server.md, doc/content/reference/api/application_webhooks.md, doc/content/reference/api/authentication.md, doc/content/reference/api/end_device.md, doc/content/reference/api/end_device_claiming.md, doc/content/reference/api/events.md, doc/content/reference/api/field-mask.md, doc/content/reference/api/gateway.md, doc/content/reference/api/gateway_server.md, doc/content/reference/api/gateway_server_mqtt.md, doc/content/reference/api/network_server.md, doc/content/reference/api/organization.md, doc/content/reference/api/storage_integration.md, doc/content/reference/api/tenant.md, doc/content/reference/api/user.md, doc/content/reference/data-retention/_index.md, doc/themes/the-things-stack/layouts/partials/proto/field-type.html, doc/themes/the-things-stack/layouts/shortcodes/api-refs.html, doc/themes/the-things-stack/layouts/shortcodes/proto/enum.html, doc/themes/the-things-stack/layouts/shortcodes/proto/message.html, doc/themes/the-things-stack/layouts/shortcodes/proto/method.html
Add the missing messages and enums to respective API sections. Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/362
- Add all missing messages and enums
- Add shortcode to check for missing enums
=> Add missing API messages and enums (fix broken links)

doc/content/gateways/ciscowirelessgateway/_index.md, doc/content/gateways/lora-basics-station/cups.md, doc/content/gateways/lora-basics-station/lns.md, doc/content/gateways/lorix-one/udp.md, doc/content/gateways/mikrotik-knot/_index.md, doc/content/gateways/mikrotik-ltap/_index.md, doc/content/gateways/mikrotikrouterboard/_index.md, doc/content/gateways/nasysoutdoorgateway/_index.md, doc/content/gateways/tektelickonamicro/udp.md, doc/content/gateways/thethingskickstartergateway/_index.md, doc/content/gateways/troubleshooting/_index.md, doc/content/gateways/ursalinkug8x/packet-forwarder.md, doc/content/getting-started/console/login/_index.md, doc/content/getting-started/quick-start/index.md, doc/content/getting-started/server-addresses/_index.md, doc/content/getting-started/upgrading/_index.md, doc/content/getting-started/what-is-tts/_index.md
Add a page with server addresses for the different deployments.
=> Add server addresses page

doc/content/reference/configuration/the-things-stack.md
Closes #444
Perhaps we might want to support reading a base64-encoded string from the license file as well, but I think it's important to have the expected format documented, to prevent confusion in the future.
=> Clarify license key format

doc/content/getting-started/installation/_index.md, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/troubleshooting.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/501
- Add some forbidden errors to troubleshooting
- Add video guides
- Fix bad DB uri in enterprise storage integration configuration
=> Improve installation guide

doc/content/reference/configuration/network-server.md
Documentation for https://github.com/TheThingsNetwork/lorawan-stack/pull/4314
=> Document `ns.cluster-id` configuration option

doc/content/reference/purge/_index.md
Add doc for purging entities, re https://github.com/TheThingsNetwork/lorawan-stack/issues/3585
TODO: Add a screenshot from the console when the feature is implemented
=> doc: Add purge reference

doc/content/getting-started/cli/_index.md, doc/content/reference/cli/troubleshooting.md, doc/content/reference/stripe/_index.md
Add a small section to be expanded later with CLI errors
=> doc: Add CLI troubleshooting

doc/content/getting-started/cloud-hosted/addresses.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/406#issuecomment-880390048
=> doc: Add AWS IP note

doc/content/getting-started/aws/ecs/monitoring/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/537
Added troubleshooting section per issue
=> doc: Add Prometheus troubleshooting

doc/content/getting-started/packet-broker/configure/_index.md, doc/content/getting-started/packet-broker/configure/registration.md, doc/content/getting-started/packet-broker/configure/routing-policies.md, doc/content/getting-started/packet-broker/connect.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/522
=> Add packetbroker TTN forwarding example

doc/content/integrations/mqtt/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/486
=> Document supported QOS value for MQTT server

doc/themes/the-things-stack/layouts/partials/schema/schema.html
=> Fix image links

doc/themes/the-things-stack/layouts/partials/schema/icon.html
Fixes images
Made images use correct URL
=> doc: Fix images

doc/content/gateways/thethingsindoorgateway/_index.md
Update ttig claiming options
- Update ttig claiming options
- Add CLI
=>  Update ttig claiming options

doc/content/gateways/ciscowirelessgateway/_index.md, doc/content/gateways/cloudgate/_index.md, doc/content/gateways/lora-basics-station/_index.md, doc/content/gateways/lora-basics-station/lns.md, doc/content/gateways/mikrotik-knot/_index.md, doc/content/gateways/mikrotik-ltap/_index.md, doc/content/gateways/mikrotikrouterboard/_index.md, doc/content/gateways/multitechconduit/_index.md, doc/content/gateways/multitechconduit/lbs.md, doc/content/gateways/multitechconduit/udp.md
Improve docs based on feedback from multitech
=> Improve multitech docs

doc/content/reference/purge/_index.md
Add purge CLI commands. CLoses https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/468
Updating CLI docs is blocked on https://github.com/TheThingsNetwork/lorawan-stack/issues/4378
=> doc: Add purge CLI commands

doc/content/integrations/storage/enable.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/479
=> doc: Add disable storage integration instructions

doc/content/whats-new/3.14.1.md, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.UserRights.yml, doc/data/api/tti.lorawan.v3/messages/SearchTenantsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/Application.yml, doc/data/api/ttn.lorawan.v3/messages/CUPSRedirection.yml, doc/data/api/ttn.lorawan.v3/messages/ClaimGatewayRequest.yml, doc/data/api/ttn.lorawan.v3/messages/Client.yml, doc/data/api/ttn.lorawan.v3/messages/Gateway.yml, doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.UserRights.yml, doc/data/api/ttn.lorawan.v3/messages/Organization.yml, doc/data/api/ttn.lorawan.v3/messages/PacketBrokerInfo.yml, doc/data/api/ttn.lorawan.v3/messages/PacketBrokerRegisterRequest.yml, doc/data/api/ttn.lorawan.v3/messages/SearchApplicationsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/SearchClientsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/SearchEndDevicesRequest.yml, doc/data/api/ttn.lorawan.v3/messages/SearchGatewaysRequest.yml, doc/data/api/ttn.lorawan.v3/messages/SearchOrganizationsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/SearchUsersRequest.yml, doc/data/api/ttn.lorawan.v3/messages/User.yml, doc/data/api/ttn.lorawan.v3/services/Pba.yml, doc/data/ttn-lw-cli.yml
=> doc: Release v3.14.1 documentation update

doc/data/glossary.yml
Add glossary entries from https://github.com/TheThingsNetwork/lorawan-stack/issues/4290#issuecomment-887790141
=> doc: Add glossary entries

doc/content/getting-started/cli/installing-cli/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/469
- Clarify ttn-lw-cli vs tti-lw-cli
=> doc: Clarify cli differences

doc/content/integrations/storage/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/516
=> doc: Note storage delay

doc/content/gateways/troubleshooting/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/517
=> doc: Add gateway FAQ

doc/content/getting-started/troubleshooting/_index.md, doc/content/reference/purge/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/512
=> doc: Add entity taken error

doc/content/reference/configuration/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/431
Add note that configuration options only work for Open Source and Enterprise
=> doc: Add configuration options note

doc/content/getting-started/packet-broker/configure/routing-policies.md, doc/content/reference/pb-routing/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/501
=> doc: Add packet broker routing defaults table

doc/content/getting-started/aws/ami/post-deployment/_index.md, doc/content/getting-started/aws/ami/troubleshooting/_index.md, doc/content/getting-started/aws/ami/updating/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/426
Improved AMI update guide
=> doc: Fixes to AMI update docs

doc/content/gateways/adding-gateways/_index.md
=> doc: Document setting gateway antenna gain

doc/content/reference/tenant-management/_index.md, doc/themes/the-things-stack/layouts/shortcodes/cli-only.html
Closes #347 
Documenting basics for tenant management, like authentication and basic operations.
=> doc: Document tenant management

doc/content/whats-new/3.14.2.md, doc/data/api/ttn.lorawan.v3/messages/EndDeviceBrand.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.FirmwareVersion.Profile.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.FirmwareVersion.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.Photos.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.Reseller.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.Videos.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.yml, doc/data/api/ttn.lorawan.v3/messages/GetEndDeviceBrandRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GetEndDeviceModelRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GetPayloadFormatterRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GetStoredApplicationUpCountRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GetStoredApplicationUpCountResponse.yml, doc/data/api/ttn.lorawan.v3/messages/GetTemplateRequest.yml, doc/data/api/ttn.lorawan.v3/messages/LRFHSSDataRate.yml, doc/data/api/ttn.lorawan.v3/messages/ListEndDeviceBrandsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/ListEndDeviceModelsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/MACSettings.yml, doc/data/api/ttn.lorawan.v3/services/ApplicationUpStorage.yml, doc/data/ttn-lw-cli.yml
=> doc: Update v3.14.2 release docs

doc/content/reference/configuration/the-things-stack.md, doc/content/reference/resource-limiting/_index.md, doc/data/resource-limiting.yml, doc/themes/the-things-stack/layouts/shortcodes/resource-limiting.html
Documentation for https://github.com/TheThingsIndustries/lorawan-stack/pull/2879
cc @KrishnaIyer.
Marked as draft until implementation is merged.
=> Document resource limits

doc/content/getting-started/aws/ami/deployment-guide/_index.md, doc/content/getting-started/aws/ami/troubleshooting/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/565
=> doc: Improve documentation regarding RDS and Redis

doc/content/integrations/storage/configuration.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/521
@neoaggelos do these options only configure an underlying TimescaleDB database? Is there a description somewhere of what values they accept and what they do?
=> doc: Add timescaledb config options

doc/archetypes/section-bundle/_index.md, doc/content/getting-started/migrating/device-json.md, doc/themes/the-things-stack/assets/css/common/global.scss
Proposal for layout fix for tables
The best solution I can come up with, is we leave tables as is by default (so we don't unexpectedly break anything) and add a class to manually define tables using fixed width layouts to fix tables on a case by case basis.
That means wrapping tables in a helper div
```
<div class="fixed-table table-name>
| Header 1 | Header 2 |
|---|---|
| Col 1 | Col 2 |
</div>
```
and then applying column widths using a specific css class per table
```
.fixed-table {
table {
display: table;
table-layout: fixed;
}
td,th {
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
}
}
.table-name {
th:nth-child(1) {
width: 10em;
}
th:nth-child(2) {
width: 6em;
}
}
```
Produces results like this with manual tweaking:
@kschiffer @htdvisser @nejraselimovic @pierrephz …
=> doc: Change table layout

doc/content/reference/pb-routing/_index.md
Fix broken reference in packet broker section, from #550 
=> Fix broken packet broker reference

doc/content/getting-started/aws/ecs/updating/_index.md
Documentation for https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/500
=> doc: V3.15.0 TimescaleDB update

doc/content/reference/api/authentication.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/559
=> doc: Note about using API key

doc/content/gateways/troubleshooting/_index.md
=> doc: Add gateway location troubleshooting

doc/content/getting-started/migrating/migrating-from-v2/_index.md
=> doc: Fix migration deadline

doc/content/getting-started/server-addresses/_index.md
Fix server address examples
- Fix server address examples
=> Fix server address examples

doc/content/reference/gateway-rtt/_index.md
=> Document Gateway RTT

doc/config/_default/config.toml, doc/content/reference/api/tenant.md, doc/content/whats-new/3.15.0.md, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.UserLogin.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.JoinServer.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.yml, doc/data/api/ttn.lorawan.v3/messages/Gateway.yml, doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsResponse.VersionInfo.yml, doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsResponse.yml, doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.UserLogin.yml, doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.yml, doc/data/api/ttn.lorawan.v3/services/Configuration.yml, doc/data/ttn-lw-cli.yml
=> doc: Add v3.15.0 release docs

doc/content/getting-started/migrating/faq.md
=> Migration FAQ doc

doc/content/getting-started/aws/ecs/deployment/_index.md
Document new template https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/501
Added information about new template
...
=> doc: Add information about template 4-2c

doc/content/devices/troubleshooting/_index.md
=> doc: Add device registration troubleshooting

doc/content/getting-started/cloud-hosted/_index.md, doc/content/getting-started/packet-broker/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/589
=> doc: Add status page refs for Cloud Hosted and Packet Broker

doc/content/devices/adding-devices/_index.md
=> doc: Add note about using all zeros JoinEUI

doc/config/_default/config.toml
Seems like the forum URL changed
=> doc: Update forum URL

doc/content/integrations/webhooks/creating-webhooks.md
User reported that webhook.site is easier to test with than postbin, so suggesting it instead.
=> doc: Suggest webhook.site for testing

CONTRIBUTING.md, doc/config/_default/config.toml, doc/content/getting-started/troubleshooting/_index.md, doc/themes/the-things-stack/layouts/index.html, doc/themes/the-things-stack/layouts/shortcodes/forum-url.html
=> Fix all forum urls

doc/content/reference/lbs-implementation-guide/implementation-details.md
Closes #409 
- Document LBS downlink scheduling
=>  Document LBS downlink scheduling

doc/content/gateways/troubleshooting/_index.md, doc/content/getting-started/console/troubleshooting/_index.md, doc/content/getting-started/troubleshooting/_index.md, doc/content/reference/last-activity/_index.md
Create console troubleshoot and add Last seen / last activity
=> doc: Create console troubleshooting

doc/content/getting-started/console/troubleshooting/_index.md
Reverts changes introduced and accidentally deleted in #612
=> doc: Revert Console troubleshooting entry

doc/content/getting-started/migrating/gateway-migration.md
Add explicit note not to follow migration directions for TTIG
=> doc: Add gateway claiming note to migration doc

doc/content/devices/downlink-queue-ops/_index.md
=> doc: Document downlink queue limit

doc/content/getting-started/installation/_index.md, doc/content/getting-started/installation/balena/index.md, doc/content/getting-started/installation/certificates.md, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/running-the-stack.md, doc/content/getting-started/installation/troubleshooting.md
Clarify installation foreword, and remove notes where unnecessary.
=> doc: Installation foreword

doc/content/getting-started/aws/ecs/interop/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/505
Interop is going to actually work from version 3.16.0
Added interop documentation
@johanstokking can you go through it and fix issues?
@benolayinka can you help me with style?
=> doc: Add interop deployment documentation

doc/content/integrations/webhooks/troubleshooting.md
=> doc: Create Webhooks troubleshooting section

doc/content/gateways/troubleshooting/_index.md
=> doc: Add support info

doc/content/integrations/storage/_index.md, doc/content/integrations/storage/configuration.md, doc/content/integrations/storage/enable.md, doc/content/integrations/storage/retrieve.md
=> doc: Add retention period info, improve readability

doc/content/getting-started/cloud-hosted/tti-join-server/register-devices.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/640
=> doc: Document JoinEUI/AppEUI restriction

doc/content/ttn-lw-cli/ttn-lw-cli_external-users_delete.md, doc/content/whats-new/3.16.1.md, doc/data/api/ttn.lorawan.v3/messages/DownlinkQueueRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GatewayConnectionStats.SubBand.yml, doc/data/api/ttn.lorawan.v3/messages/GatewayStatus.yml
=> doc: v3.16.1 release docs

doc/content/getting-started/migrating/_index.md, doc/content/getting-started/migrating/major-changes.md, doc/content/getting-started/migrating/migrating-from-v2/_index.md, doc/content/reference/api/_index.md
Updates based on feedback widget
=> Minor updates to migration docs

doc/content/devices/troubleshooting/_index.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md
=> doc: Document fixes for missing uplinks

doc/content/getting-started/aws/ecs/interop/_index.md
Documentation for https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/567
Updated information regarding interoperability
=> doc: Update interop documentation

doc/content/reference/api/application_webhooks.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_list.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_set.md, doc/content/whats-new/3.16.2.md, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhook.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhookHealth.WebhookHealthStatusHealthy.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhookHealth.WebhookHealthStatusUnhealthy.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhookHealth.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhookTemplate.yml, doc/data/api/ttn.lorawan.v3/messages/AsConfiguration.Webhooks.yml, doc/data/api/ttn.lorawan.v3/messages/AsConfiguration.yml, doc/data/api/ttn.lorawan.v3/messages/ContactInfoValidation.yml, doc/data/api/ttn.lorawan.v3/messages/GatewayConnectionStats.yml
=> doc: Add v3.16.2 release docs

doc/content/getting-started/aws/ecs/database-operations/_index.md
Document storage-db intialization
Document storage-db intialization
=> doc: Document storage-db intialization

doc/content/getting-started/installation/configuration/index.md
Fix broken link pointed towards Custom Certificate Authority.
N/A
- remove extra round bracket pair
N/A
=> doc: Fix broken link custom-certificate-authority

doc/content/getting-started/aws/ecs/interop/_index.md
Fix an oversight in the documentation
Documented value was wrong
=> doc: Fix interop documentation

doc/content/integrations/cloud-integrations/aws-iot/default/messages.md
=> doc: Fix topic from /ack to /nack

doc/content/whats-new/3.16.3.md
=> doc: Update v3.16.3 release docs

doc/content/getting-started/cli/configuring-cli/_index.md, doc/content/getting-started/cloud-hosted/_index.md, doc/content/getting-started/console/_index.md, doc/themes/the-things-stack/layouts/shortcodes/tenant-cluster-selector.html
Closes #691 
Any special notes about using eu2 cluster are welcome
=> doc: Add CH eu2 cluster info

doc/content/devices/adding-devices/_index.md, doc/content/integrations/cloud-integrations/azure-iot-hub/devices.md, doc/content/reference/api/field-mask.md
Update EUI description for end device creation. Refs: https://github.com/TheThingsNetwork/lorawan-stack/pull/5035
Update EUI description for end device creation.
=> Update EUI description for end device creation

doc/content/gateways/lora-basics-station/cups.md
Remove outdated note on cups
- Remove outdated note on cups
=> Remove outdated note on cups

doc/content/gateways/troubleshooting/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/686#event-5851012472
=> doc: Remove TTI contact info, add temporary workaround

doc/content/devices/troubleshooting/_index.md
Note for old forum issue https://www.thethingsnetwork.org/forum/t/why-is-my-abp-device-not-seen-in-v3/53300/15
=> doc: Add note for dropped msgs on ABP

doc/config/_default/config.toml, doc/content/whats-new/3.17.1.md
=> doc: Add v3.17.1 release docs

doc/content/getting-started/aws/ami/deployment-guide/_index.md, doc/content/getting-started/aws/ami/troubleshooting/_index.md, doc/content/getting-started/aws/ami/updating/_index.md
Closes #727 
A few minor fixes
=> Fixes to the AWS Marketplace documentation

doc/content/gateways/troubleshooting/_index.md
=> doc: Document connection stats for disconnected gtw

doc/content/reference/configuration/application-server.md, doc/content/reference/configuration/console.md, doc/content/reference/configuration/gateway-server.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/configuration/network-server.md, doc/content/reference/configuration/packet-broker-agent.md, doc/content/reference/configuration/the-things-stack.md
=> Document missing configuration options

doc/content/getting-started/installation/_index.md, doc/content/getting-started/installation/troubleshooting.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/698
I applied everything that was required in the issue, but I'm not sure if I understand the installation requirements part for multi-tenant and offline deployments, so an explanation would be really nice
=> doc: Add installation note and troubleshooting entries

doc/content/gateways/multitechconduit/lbs.md
=> doc: Clarify CUPS API key instructions

doc/content/getting-started/aws/ecs/troubleshooting/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/743
Added information on AWS ECS troubleshooting
=> doc: Add infomation on AWS ECS troubleshooting

doc/content/reference/data-formats/_index.md
=> doc: Add network and device hardware info to uplink data format

doc/content/devices/adding-devices/_index.md, doc/content/gateways/adding-gateways/_index.md, doc/content/getting-started/api/_index.md
=> doc: Document adding ABP devices and gateways using the API

doc/content/getting-started/installation/troubleshooting.md
=> doc: Add installation troubleshooting entries

doc/content/getting-started/migrating/device-json.md
When reading the documentation for the creation of the cli integration tests I had some misinterpretations where I assumed that the format described in the `migrating/device-json` page would be applicable to the CLI.
- Update format presented for `devices.json`
- Add small section explaining file format and reference to instructions on how to use file to import devices
=> Update CLI input regarding creation of end-devices via json

doc/config/_default/config.toml, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_reset.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.18.0.md, doc/data/api/ttn.lorawan.v3/messages/MACSettings.yml
=> doc: Add v3.18.0 release docs

doc/content/reference/resource-limiting/_index.md
=> doc: Small notes for resource limiting

.github/workflows/issue-triage.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml
This upgrades the dependencies of our Github Actions workflows.
n/a
- Upgrade `runs-on` from `ubuntu-18.04` to `ubuntu-20.04`
- Upgrade `actions/setup-go` from `v2` to `v3`
- And upgraded `go-version` from `~1.15` to `~1.17`
- Upgrade `actions/setup-node` from `v2` to `v3`
- And upgraded `node-version` from `~14` to `~16`
- Upgrade `actions/github-script` from `v3` to `v6`
- And patched scripts to use `rest`, since REST API is no longer on the `github` object directly.
n/a
=> Upgrade dependencies of Github Actions workflows

doc/content/devices/troubleshooting/_index.md
=> doc: Add device troubleshooting entries

doc/content/gateways/thethingsindoorgateway/_index.md
Add notes for using TTIGs on different LNS
- Add notes for using TTIGs on different LNS
=> Add notes for using TTIGs on different LNS

doc/content/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted.md, doc/content/getting-started/cloud-hosted/tti-join-server/register-devices.md
Updating AppEUI/JoinEUI info for The Things Join Server as requested [here](https://github.com/TheThingsIndustries/lorawan-stack-support/issues/744#issuecomment-1064303400) + closing #806
=> doc: Fix AppEUI info

doc/content/getting-started/aws/ecs/best-practices/_index.md
References https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/758
Added "Best Practices" section
Am I missing something important? @KrishnaIyer 
=> Add ECS best practices

doc/content/getting-started/aws/ami/best-practices/_index.md
Pretty much copy-paste of https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/812 but for a single-AMI deployment.
Added best practices for a single-AMI deployment.
=> doc: Add PAYG best practices

doc/content/getting-started/aws/ami/troubleshooting/_index.md
Closes #817 
Addressed a few minor improvements (links).
=> doc: Improve AWS AMI troubleshooting doc

doc/content/getting-started/installation/_index.md, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/running-the-stack.md
=> doc: Address installation section feedback

doc/content/getting-started/upgrading/_index.md
Closes #713 
- Add postgres upgrade note
...
=> Add postgres upgrade note

doc/content/getting-started/aws/ecs/updating/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/815#issuecomment-1073521033
Added a note about database migrations
=> Fix docs updates

doc/content/gateways/_index.md, doc/content/gateways/adding-gateways/_index.md, doc/content/getting-started/packet-broker/_index.md
Add note about TTN mapper and Packet Broker
@johanstokking you're a reviewer just to double check that we're not crossing some boundary here linking to TTN mapper
=> doc: Add ttn mapper note

doc/content/reference/interop-repository/_index.md
Update Join Server interop configuration
- Add missing config options
- Mention LoRaWAN Backend Interfaces clearly, as that is what people likely use to search docs
- Document The Things Join Server config
@KrishnaIyer is the main reviewer
=> Update Join Server interop configuration

doc/content/reference/branding/_index.md
=> doc: Link to tenant settings -> branding options

doc/content/getting-started/installation/configuration/docker-compose-custom-certificates.yml, doc/content/getting-started/installation/configuration/docker-compose-enterprise.yml, doc/content/getting-started/installation/configuration/docker-compose-open-source.yml, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/upgrading/_index.md
Closes #835
I'm not sure if the process for deleting, recreating and restoring the `ttn_lorawan` database I described is the most optimal one, but it works. Suggestions to improve this are warmly welcome
=> doc: Replace CockroachDB with PostgreSQL

doc/content/devices/device-claiming/claim-devices.md, doc/content/devices/device-claiming/make-device-claimable.md, doc/content/devices/generate-qr-code/_index.md
=> doc: Improve QR and claiming docs

doc/content/getting-started/aws/ecs/database-operations/_index.md
Mention Network Operations Center OAuth client in the docs.
Mentioned Network Operations Center OAuth client in the docs.
=> Mention the NOC OAuth client

doc/content/reference/fuota/_index.md
=> doc: Add FUOTA doc

doc/content/getting-started/aws/ami/deployment-guide/_index.md
Docs for https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/648
Docs for https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/648
=> doc: Add information about TLS certificate in AMI templates

doc/content/integrations/cloud-integrations/kaa/index.md
=> Kaa IoT platform edits

doc/content/getting-started/installation/_index.md
Updated YouTube Link for TTSE configuration. Was dev repo, now intro to install TTS in 6 min 
...
updated youtube link
...
=> TTSE  installation configuration youtube link updated

doc/content/devices/end-device-templates/assigning-euis.md, doc/content/getting-started/cloud-hosted/tti-join-server/register-devices.md
=> doc: Update IEEE Standards Association references

doc/content/getting-started/aws/ami/updating/_index.md
Add note on Let's Encrypt Ratelimit
- Add note on Let's Encrypt Ratelimit
=> Add note on Let's Encrypt Ratelimit

doc/content/ttn-lw-cli/ttn-lw-cli_completion_bash.md, doc/content/ttn-lw-cli/ttn-lw-cli_completion_fish.md, doc/content/ttn-lw-cli/ttn-lw-cli_completion_powershell.md, doc/content/ttn-lw-cli/ttn-lw-cli_completion_zsh.md
References https://github.com/TheThingsNetwork/lorawan-stack/issues/5397
The `completion` command from `ttn-lw-cli` doesn't accept an argument to determine the autocomplete shell type.  I updated the documentation to include the flag in order to avoid confusion like what I assume it happened in the case of the mentioned issue.
<details><summary>Screenshots</summary>
</details>
- Added the `--shell` flag in the `ttn-lw-cli complete` examples.
I'm wondering if I should add the same `--shell` flag for the bash example or not, since the default always is to generate a bash script I'm inclined to leave it without it.
=> Add shell flag to CLI completion command examples

doc/content/devices/adding-devices/_index.md, doc/content/getting-started/migrating/import-devices.md
=> doc: Update adding devices in bulk with CSV, reorganize Adding Devices

doc/content/getting-started/api/_index.md, doc/content/reference/api/end_device.md
=> doc: Add end device creation via API ref

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get-default-mac-settings.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.20.1.md, doc/data/api/tti.lorawan.v3/messages/GatewayConnectivityTimes.yml
=> doc: Add v3.20.1 release docs

doc/content/gateways/gateway-claiming/_index.md
Add note on gateway claiming
- Add a note that the gateway claiming section is only applicable to UDP
=> Add note on gateway claiming

doc/content/getting-started/upgrading/_index.md
=> doc: Minor changes in Upgrading TTS section

doc/content/devices/troubleshooting/_index.md
=> doc: Resolve unaccessible device in the Console error

doc/content/reference/api/authentication.md
Adds information about OAuth client creation.
Closes #439
...
Added TTN CLI command for creating an OAuth client.
...
=> doc: Add information about OAuth client creation

doc/content/getting-started/aws/ecs/troubleshooting/_index.md
=> doc: Add troubleshooting entry for AWS ECS

doc/content/getting-started/migrating/migrating-from-ce-to-ch/establish-new-session/_index.md
=> doc: Add note about persisting session on CE during registration on CH

doc/content/reference/configuration/identity-server.md
This pull request adds the configuration reference for the new entity limits options added in https://github.com/TheThingsIndustries/lorawan-stack/pull/3296
- Document new configuration options for entity limits
none
=> Add entity limits configuration reference

doc/content/integrations/webhooks/webhook-templates/format.md, doc/content/integrations/webhooks/webhook-templates/instantiation.md
References https://github.com/TheThingsNetwork/lorawan-stack/pull/5655
- `integrations/webhooks/webhook-templates/format/`
- `integrations/webhooks/webhook-templates/instantiation/`
- add `Field Mask` section in `integrations/webhooks/webhook-templates/format/`
- add `Instantiation of Field Mask` section in `integrations/webhooks/webhook-templates/instantiation/`
nil
=> Add `field_mask` to webhook docs

doc/content/getting-started/aws/ecs/database-operations/_index.md, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/running-the-stack.md, doc/content/reference/configuration/network-operations-center.md
Closes #932 
@johanstokking there's no much documentation available for NOC as far as I can see, so could you add some useful info for this PR if you think it's necessary? I generally think [this doc](https://www.thethingsindustries.com/docs/getting-started/installation/configuration/#understanding-the-things-stack-configuration) could be better, and I see some stuff missing (for example device claiming server config), so I'll make a separate issue for that.
=> doc: Replace init with migrate, add NOC config info

doc/content/getting-started/aws/ecs/mutual-tls/_index.md
Refs; https://github.com/TheThingsIndustries/lorawan-stack/pull/3397
https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/681
- Add new mTLS Section
=> Document mTLS support

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get-default-mac-settings.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_list-bands.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.22.1.md
=> doc: Add v3.22.1 release docs

doc/content/getting-started/migrating/migrate-from-chirpstack.md
=> Update title for SEO

doc/content/integrations/cloud-integrations/azure-iot-central/deployment.md
Clarify activation of the Destinations tab.
=> doc: Azure IOT central doc clarification

doc/content/gateways/troubleshooting/_index.md
=> doc: Update gateway troubleshooting list

doc/content/getting-started/aws/ecs/mutual-tls/_index.md
Refs; https://github.com/TheThingsIndustries/lorawan-stack-aws/issues/672
- Add new section on mTLS
=> Document mTLS gateway connections

doc/content/getting-started/migrating/device-csv.md, doc/data/frequency-plans.yml
I wrote more details in [here](https://github.com/TheThingsIndustries/lorawan-stack-support/issues/880#issuecomment-1315575696) but the short end of the story is that one of the values in the CSV example does not work.
- Change value of `model_id`
- Update Frequecy dependencies ( ran `make init` )
=> Update CSV File Reference

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/reference/api/end_device.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get-default-mac-settings.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_list-bands.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.22.2.md, doc/data/api/ttn.lorawan.v3/messages/MACSettings.yml, doc/data/api/ttn.lorawan.v3/messages/ZeroableFrequencyValue.yml
Closes #989
TODO: Add the release date
=> doc: Add v3.22.2 release docs

doc/content/getting-started/installation/_index.md
=> doc: Note about deployment choice for high availability/throughput

doc/content/getting-started/user-management/user/_index.md, doc/content/reference/id-eui-constraints/index.md
=> doc: Notes on using IDs after purge

doc/content/getting-started/aws/ecs/deployment/_index.md
=> doc: Document Prometheus username and pass

doc/content/gateways/models/thethingsindoorgateway/_index.md
Add that TTIG must hard reset to update config.
=> doc: Add that TTIG must hard reset to update config

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get-default-mac-settings.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_list-bands.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.23.0.md, doc/data/api/ttn.lorawan.v3/messages/CreateClientEmailMessage.yml
=> doc: Add v3.23.0 release docs

doc/content/integrations/adding-applications/_index.md
=> doc: Note on skip payload encryption setting

doc/content/getting-started/aws/ecs/deployment/_index.md
=> doc: Add note about required 2-5-db-timescale template

doc/content/getting-started/installation/troubleshooting.md
=> doc: Document resolving Grafana permissions issue

doc/content/getting-started/aws/ecs/interop/_index.md, doc/content/reference/configuration/the-things-stack.md, doc/content/reference/interop-repository/_index.md
Documentation for https://github.com/TheThingsIndustries/lorawan-stack/pull/3564
References https://github.com/TheThingsNetwork/lorawan-stack/issues/5982
- Fix TLS mutual authentication configuration text: https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/720 wasn't documented
- Document support for TLS client authentication via key vault in JS interop client
- Document how to configure the AWS key vault with Private CA
=> Document TLS client configuration

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/whats-new/3.23.2.md, doc/data/api/ttn.lorawan.v3/messages/SearchEndDevicesRequest.yml
=> doc: Add v3.23.2 release docs

doc/content/reference/configuration/application-server.md, doc/content/reference/configuration/device-claiming-server.md, doc/content/reference/configuration/network-server.md, doc/content/reference/interop-repository/_index.md
This documents the NSID settings as well as end device claiming options for the Device Claiming Server.
References https://github.com/TheThingsNetwork/lorawan-stack/pull/6050
- Update NS component configuration
- Update DCS component configuration
- Update AS component configuration to reflect new config options
@KrishnaIyer this does not include `dcs.glcs.*` options; do we need to document those as well?
=> Document NSID settings and DCS component

doc/content/gateways/models/thethingskickstartergateway/_index.md, doc/content/getting-started/server-addresses/_index.md
Add server address for TTKG
This is a simple change.
- Add server address for TTKG
=> Add server address for TTKG

doc/content/integrations/cloud-integrations/aws-iot/uninstall.md
=> doc: Note about deleting devices from AWS IoT

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/whats-new/3.24.1.md, doc/data/api/ttn.lorawan.v3/messages/SimulateDataUplinkParams.yml, doc/data/api/ttn.lorawan.v3/messages/SimulateJoinRequestParams.yml, doc/data/api/ttn.lorawan.v3/messages/SimulateMetadataParams.yml
=> doc: Add v3.24.1 release docs

doc/content/getting-started/installation/configuration/docker-compose-enterprise.yml, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/troubleshooting.md
Closes #1047 
Wasn't sure about config options I added, but I felt like those should be listed in installation files, and not only documented as a quickfix in Troubleshooting guide. Any inputs there?
=> doc: Troubleshooting installation

doc/content/devices/adding-devices/_index.md
Make it clear that we require a TR005 LoRaWAN® Device Identification QR Code to onboard a device. With link to the loRaAlliance docs
=> Update onboarding devices using QR codes

doc/content/getting-started/installation/_index.md, doc/content/getting-started/installation/certificates.md, doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/running-the-stack.md
Update installation guide, fixed some lines in the config file preview
=> Update installation guide

doc/content/getting-started/kubernetes/_index.md, doc/content/getting-started/kubernetes/configuration/_index.md, doc/content/getting-started/kubernetes/install-charts/_index.md, doc/content/getting-started/kubernetes/monitoring/_index.md, doc/content/getting-started/kubernetes/preparation/_index.md, doc/content/getting-started/kubernetes/prerequisites/_index.md, doc/content/getting-started/kubernetes/troubleshooting/_index.md
Add k8s installation guide
- Add Kubernetes section.
=> Add k8s installation guide

doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-custom-certificates.yml, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-open-source.yml
Closes #1054 
Wasn't sure if this is just for Enterprise config file (as mentioned in the issue) so I added it to all config files
=> doc: Add DCS Base URL in config files

doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/running-the-stack.md
=> doc: Update installation guide

doc/content/getting-started/aws/ecs/deployment/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1066
- Add note about uploading EDCS config file
When deploying TTS it turned out this file was necessary.
=> Add note about uploading EDCS config file

doc/config/_default/config.toml, doc/content/getting-started/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications.md, doc/content/whats-new/3.24.2.md, doc/data/api/ttn.lorawan.v3/messages/AuthorizeApplicationRequest.yml, doc/data/api/ttn.lorawan.v3/services/EndDeviceClaimingServer.yml, doc/data/api/ttn.lorawan.v3/services/EndDeviceRegistry.yml, doc/data/commands/ttn-lw-cli.json
=> doc: Add v3.24.2 release docs

doc/content/getting-started/aws/ecs/database-operations/_index.md, doc/content/getting-started/aws/ecs/deployment/_index.md
Ref https://github.com/TheThingsIndustries/lorawan-stack-aws/issues/740
- Add information about setting up the Plugins Bucket
- Fix information about initialising (migrating) IS database
nil
=> Add information about the Plugins Bucket

doc/content/getting-started/packet-broker/troubleshooting.md
=> doc: Add support contact

.github/workflows/pull_request.yml, .github/workflows/release.yml, doc/config/gh-pages/config.toml, doc/themes/the-things-stack/layouts/_default/baseof.html, doc/themes/the-things-stack/layouts/partials/gtm_body.html, doc/themes/the-things-stack/layouts/partials/gtm_head.html, doc/themes/the-things-stack/layouts/partials/head/head.html
Closes #1084
- Remove googleAnalytics environment variable 
- Add `HUGO_PARAMS_GTM_ID` environment variable 
- Add `gtm_head.html` and `gtm_body.html` template partials.
@adriansmares I don't have access to the github environment variable so can you please set 
`HUGO_PARAMS_GTM_ID` to `GTM-NGRDCNM` and remove the `HUGO_GOOGLEANALYTICS`
=> Add google tag manager

doc/content/the-things-stack/host/docker/configuration/index.md
This PR fixes some unclosed sections in the [`Configuration`](https://www.thethingsindustries.com/docs/the-things-stack/host/docker/configuration/#tls) part of the Docker self hosted deployment.
vs 
- Close the sections.
=> Fix unclosed sections

doc/content/reference/id-eui-constraints/index.md
Fix EUI constraints
NA. This is a simple change.
- Add a new section for EUI constraints
=> Fix EUI constraints

doc/content/devices/multicast/index.md
=> doc: Mention shared DevAddr and session keys for multicast

doc/content/gateways/troubleshooting/_index.md
=> doc: Gateway troubleshooting update

doc/content/the-things-stack/interact/cli/configuring-cli/_index.md, doc/content/the-things-stack/interact/cli/troubleshooting/_index.md
=> doc: CLI troubleshooting update

doc/config/_default/config.toml, doc/content/reference/api/end_device.md, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_reset.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_search.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.25.2.md, doc/data/api/ttn.lorawan.v3/messages/ADRSettings.DynamicMode.yml, doc/data/api/ttn.lorawan.v3/messages/GatewayConnectionStats.yml, doc/data/api/ttn.lorawan.v3/messages/TxSettings.yml
=> doc: Add v3.25.2 release docs

doc/content/gateways/troubleshooting/_index.md
=> doc: UDP gateway keep alive interval ts

doc/content/reference/api/client.md, doc/content/reference/api/end_device.md, doc/content/reference/api/tenant.md
=> doc: Update API docs

doc/content/integrations/cloud-integrations/datacake/index.md
=> doc: Reference server addrs section

doc/content/the-things-stack/host/docker/troubleshooting.md
=> doc: Document Operation timed out error

doc/content/the-things-stack/migrating/migrating-between-tts-distributions/_index.md, doc/content/the-things-stack/migrating/migrating-between-tts-distributions/establish-new-session/_index.md, doc/content/the-things-stack/migrating/migrating-between-tts-distributions/migrate-active-session/_index.md, doc/content/the-things-stack/migrating/migration-tool/_index.md, doc/content/the-things-stack/migrating/migration-tool/export-from-tts.md
=> doc: Minor updates in Migratin

doc/content/the-things-stack/cloud/billing-and-subscription-management/_index.md
=> doc: Document entity limit reached err

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_storage_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_storage_get.md, doc/content/whats-new/3.26.0.md, doc/data/api/tti.lorawan.v3/messages/ChannelLoRaPerformance.yml, doc/data/api/ttn.lorawan.v3/messages/ClaimEndDeviceRequest.yml, doc/data/api/ttn.lorawan.v3/messages/ContinuationTokenPayload.yml, doc/data/api/ttn.lorawan.v3/messages/GetStoredApplicationUpRequest.yml
=> doc: Add v3.26.0 release docs

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/whats-new/3.26.1.md
=> doc: Add v3.26.1 release docs

doc/content/gateways/models/thethingsoutdoor/_index.md
Updating TTOG docs
* Clarifying login passwords
* Updating fallback IP (this changed a good while ago)
* Updated link to latest firmware
=> Update TTOG docs

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/whats-new/3.26.2.md, doc/data/api/ttn.lorawan.v3/services/EndDeviceQRCodeGenerator.yml
=> doc: Add v3.26.2 release docs

doc/content/reference/adr/_index.md
=> doc: Update ADR documentation

doc/content/gateways/concepts/_index.md, doc/content/gateways/models/_index.md, doc/content/integrations/cloud-integrations/_index.md, doc/content/integrations/ifttt/_index.md, doc/content/integrations/lora-cloud/_index.md, doc/content/integrations/node-red/_index.md, doc/content/integrations/pubsub/_index.md, doc/content/integrations/storage/_index.md, doc/content/reference/components/_index.md, doc/content/the-things-stack/concepts/_index.md, doc/content/the-things-stack/interact/_index.md, doc/content/the-things-stack/management/_index.md
Refer to the issue 'Some readers think that certain pages have little or no content': https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1142
...
- Reworded some sentences to direct the reader's attention to the left menu.
- ...
@KrishnaIyer @nejraselimovic Can you review?
=> doc: Point to left menu

doc/config/_default/config.toml, doc/content/reference/api/application_server.md, doc/content/reference/api/end_device.md, doc/content/reference/api/network_server.md, doc/content/reference/api/storage_integration.md, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_storage_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_batch-delete.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_downlink_replace.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_storage_get.md, doc/content/whats-new/3.27.0.md, doc/data/api/ttn.lorawan.v3/messages/ApplicationDownlink.ConfirmedRetry.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationDownlink.yml, doc/data/api/ttn.lorawan.v3/messages/BatchDeleteEndDevicesRequest.yml, doc/data/api/ttn.lorawan.v3/messages/BatchGetEndDevicesRequest.yml, doc/data/api/ttn.lorawan.v3/messages/EndDeviceIdentifiersList.yml, doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.CollaboratorRights.yml, doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.yml, doc/data/api/ttn.lorawan.v3/services/AsEndDeviceBatchRegistry.yml, doc/data/api/ttn.lorawan.v3/services/EndDeviceBatchRegistry.yml, doc/data/api/ttn.lorawan.v3/services/JsEndDeviceBatchRegistry.yml, doc/data/api/ttn.lorawan.v3/services/NsEndDeviceBatchRegistry.yml, doc/data/commands/ttn-lw-cli.json
=> doc: Add v3.27.0 release docs

doc/content/whats-new/3.27.0.md
Fix what's new
- Add feature highlights to the markdown to show the `what's new` section.
=> Fix what's new

doc/content/reference/telemetry/_index.md, doc/content/reference/telemetry/cli.md, doc/content/reference/telemetry/identity_server.md
References https://github.com/TheThingsNetwork/lorawan-stack/pull/6415 
This is the introduction of the telemetry procedures present in the CLI and IS. 
- telemetry/index.md: 
- telemetry/cli.md: 
- telemetry/identity_server.md: 
- Fix components/_index.md typo
- Add telemetry/_index.md
- Add telemetry/cli.yml page
- Add telemetry/identity_server.yml page
This should be reviewed alongside the Stack PR which enables the telemetry.
=> Documentation on Telemetry procedures

doc/content/gateways/troubleshooting/_index.md
Update gateway troubleshooting
- Add notes for troubleshooting ID/EUI already used.
- My formatter auto-fixed a few issues.
=> Update gateway troubleshooting

doc/content/reference/telemetry/cli.md, doc/content/reference/telemetry/identity_server.md
Remove unused links
- Remove unused links
=> Remove unused links

doc/content/devices/multicast/index.md
Invalid JSON on page https://www.thethingsindustries.com/docs/devices/multicast/
Refer to the issue https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1170
- Removed some commas and validated
- ...
@nejraselimovic Can you review this?
=> doc: Fix JSON on page 'Multicast'

doc/content/the-things-stack/migrating/migration-tool/export-from-tts.md
The migration source `ttnv3` is renamed to `tts` in the later versions of the migration tool. Update the migration tool configuration with the below changes: 
- Replace `TTNV3` with `TTS` in the [configuration](https://www.thethingsindustries.com/docs/the-things-stack/migrating/migration-tool/export-from-tts/#configuration) guide. 
Updated Migration Tool configuration: 
In the Migration Tool configuration guide, `TTNV3` is changed to `TTS`.
Ref: https://www.thethingsindustries.com/docs/the-things-stack/migrating/migration-tool/export-from-tts/#configuration
...
=> doc: Update Migration Tool Configuration documentation

doc/content/gateways/troubleshooting/_index.md
=> doc: Update gateway troubleshooting guide

doc/content/integrations/storage/configuration.md, doc/content/reference/configuration/network-operations-center.md, doc/content/the-things-stack/host/docker/configuration/docker-compose-enterprise.yml, doc/content/the-things-stack/host/docker/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/the-things-stack/host/docker/running-the-stack.md, doc/content/the-things-stack/host/docker/troubleshooting.md, doc/content/the-things-stack/host/docker/upgrading/_index.md
References https://github.com/TheThingsIndustries/lorawan-stack/pull/3877
This PR adds a new FAQ entry for the NOC troubleshooting and updates the `docker compose` commands to their new format.
- Mention that the built-in Grafana may need a restart after a stack container restart, and mention the required `depends_on` which fixes this issue.
- Explain how to enable NOC applications and end devices views (i.e. extended access).
- Rewrite the `docker-compose ...` commands to `docker compose ...`, which is the newly standard format.
=> Network Operations Center FAQ updates

doc/content/the-things-stack/interact/api/_index.md
=> doc: API usage troubleshooting additions

doc/content/reference/federated-auth/oidc/_index.md, doc/content/reference/federated-auth/oidc/google.md, doc/content/reference/federated-auth/oidc/microsoft-entra.md
Improve OIDC documentation. Refs: https://github.com/TheThingsIndustries/lorawan-stack/issues/3835
- Move `oidc` to a subsection.
- Update index docs.
- Add a page for Gogle.
- Add a page for Microsoft entra.
=> Improve OIDC documentation

doc/content/the-things-stack/interact/api/_index.md
=> doc: Update error description

doc/content/reference/federated-auth/oidc/microsoft-entra.md
Update SSO with Microsoft Entra docs. Refs new changes https://github.com/TheThingsIndustries/lorawan-stack/pull/3900
- Use `allowed_email_domains`.
=> Update SSO with Microsoft Entra docs

doc/content/reference/rate-limiting/_index.md
Add more examples of ratelimiting
-  Add more examples of ratelimiting
=>  Add more examples of ratelimiting

doc/content/the-things-stack/host/docker/configuration/ttn-lw-stack-docker-custom-certificates.yml, doc/content/the-things-stack/host/docker/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/the-things-stack/host/docker/configuration/ttn-lw-stack-docker-open-source.yml
Fix account url in docker configuration
- Fix account url in docker configuration files
=> Fix account url in docker configuration

doc/content/the-things-stack/host/docker/troubleshooting.md
=> doc: Document database err

doc/content/reference/rate-limiting/_index.md, doc/data/rate-limiting.yml, doc/themes/the-things-stack/layouts/shortcodes/rate-limiting.html
References https://github.com/TheThingsNetwork/lorawan-stack/pull/6714
- Document the fact that URL classes exist now.
- Document the fact that caller identity is used instead of IP, when available.
=> Add rate limiting HTTP improvements documentation

doc/themes/the-things-stack/assets/css/common/global.scss
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/979
- Allow image to fill the `<figure>` container.
=> Allow image to fill the container

doc/config/_default/config.toml, doc/content/reference/api/end_device.md, doc/content/reference/api/network_server.md, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_reset.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_search.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md, doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md, doc/content/whats-new/3.28.2.md, doc/data/api/ttn.lorawan.v3/messages/RelayUplinkForwardingRule.yml, doc/data/api/ttn.lorawan.v3/messages/ServingRelayForwardingLimits.yml, doc/data/api/ttn.lorawan.v3/messages/ServingRelayParameters.yml
=> doc: Add v3.28.2 release docs

doc/content/devices/concepts/relay/_index.md, doc/content/devices/configuring-devices/relay-settings/_index.md, doc/themes/the-things-stack/assets/css/common/global.scss
References https://github.com/TheThingsNetwork/lorawan-stack/pull/6823
This PR documents the relay configuration commands.
- Document general LoRaWAN relay concepts, as a short introduction to LoRaWAN relays.
- Document the CLI commands used to configure the relay capabilities of end devices.
- Fix a bug which made text above notes to be unselectable / clickable.
=> Add relay commands documentation

doc/content/devices/models/elsys-ers-lite/_index.md
Fixed the way of obtaining AppKey. The AppKey is provided through an email when you purchase the device.
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1263
- Updated the content according to the review commnet.
- ...
@nejraselimovic @LDannijs
=> doc: Fix the way of obtaining AppKey

doc/content/the-things-stack/host/kubernetes/generic/configuration/_index.md
Closes #1274
- Add missing fields
nil
=> Add missing AWS Blob config secrets for Kubernetes deployment

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/whats-new/3.29.1.md, doc/data/api/tti.lorawan.v3/messages/AlertNotifications.yml, doc/data/api/ttn.lorawan.v3/messages/SearchAccountsRequest.yml
=> doc: Add v3.29.1 release docs

doc/content/the-things-stack/migrating/migration-tool/_index.md, doc/content/the-things-stack/migrating/migration-tool/export-from-chirpstack-v3.md
Add documentation for ChirpStack v4. Refs: https://github.com/TheThingsNetwork/lorawan-stack-migrate/pull/112
- Add CSv4
- Add separate section for CSv3
- Update options table
=> Add documentation for ChirpStack v4

doc/config/_default/config.toml, doc/content/the-things-stack/cloud/billing-and-subscription-management/_index.md
Remove the 1 year link old link to the old fee calculator
...
- ...
- ...
...
=> Remove the fee calculator link

doc/content/gateways/concepts/lora-basics-station/mtls-authentication/index.md, doc/content/gateways/concepts/mtls-authentication/index.md, doc/content/gateways/troubleshooting/_index.md, doc/content/the-things-stack/concepts/networking/_index.md, doc/content/the-things-stack/host/aws/ecs/mutual-tls/_index.md
Update documentation for Gateway mTLS. Refs: https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/948
- Add 8987 to networking docs.
- Update mTLS infrastructure instructions.
- Add separate section for gateway mTLS.
=> Update documentation for Gateway mTLS

doc/content/the-things-stack/host/aws/ecs/deployment/_index.md, doc/content/the-things-stack/host/aws/ecs/mutual-tls/_index.md
Fix broken link in mTLS doc
- Fix link
- Add note on using the `FARGATE` launch type.
=> Fix broken link in mTLS doc

doc/content/the-things-stack/host/aws/ami/troubleshooting/_index.md, doc/content/whats-new/3.19.2.md
Update v3.19.2 changelog and AMI troubleshooting
- Add note to `v3.192` changelog.
- Add section on using a specific binary in the AMI guide.
=> Update v3.19.2 changelog and AMI troubleshooting

doc/content/gateways/models/ciscowirelessgateway/_index.md, doc/content/gateways/models/ciscowirelessgateway/lbs.md, doc/content/gateways/models/ciscowirelessgateway/udp.md
=> doc: Modify Cisco IXM doc

doc/content/the-things-stack/host/aws/ecs/database-operations/_index.md
Reorder IS database migration command
- Add `is-db migrate` before the commands to create tenants, admin users etc.
=> Reorder IS database migration command

doc/content/the-things-stack/host/docker/_index.md, doc/content/the-things-stack/host/docker/certificates.md, doc/content/the-things-stack/host/docker/configuration/index.md, doc/content/the-things-stack/host/docker/running-the-stack.md, doc/content/the-things-stack/host/docker/troubleshooting.md
Update the documentation of hosting the stack on docker, closes #1295 
While testing out hosting the stack for myself i came across some things i wanted to see improved.
- Update youtube links
- Shuffle around certificates section (better legibility and clearer explanation)
- Overall better distinction between explanation and instructions
- Better step-by-step instructions in configuration section
- Admin id needs to be lowercase
- Add `key permission denied` to troubleshoot instead of just the text
...
=> Update docs for hosting stack on docker

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/whats-new/3.29.2.md
=> doc: Add v3.29.2 release docs

doc/content/api/concepts/auth/_index.md, doc/content/api/concepts/lora-gateway/_index.md, doc/content/api/concepts/troubleshooting/_index.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1301
- Basically fixed items in the issue.
=> Minor fixes to the API documentation

doc/content/the-things-stack/host/aws/ecs/architecture/_index.md, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/the-things-stack/host/aws/ecs/database-operations/_index.md, doc/content/the-things-stack/host/aws/ecs/deployment/_index.md, doc/content/the-things-stack/host/aws/ecs/mutual-tls/_index.md, doc/content/the-things-stack/host/aws/ecs/prerequisites/_index.md, doc/content/the-things-stack/host/aws/ecs/updating/_index.md
References https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/1047
- Remove trailing white space from ECS template documentation.
- Rename templates as done in the linked PR.
- This PR shouldn't be merged until we release `v3.30.0`
A subsequent PR will document the tenant resource monitoring templates themselves, to be merged once the stable release is done.
=> Update ECS template numbering

doc/content/reference/adr/_index.md
Refs: https://github.com/TheThingsNetwork/lorawan-stack/pull/7012
- Document configuring NbTrans overrides via CLI and API.
=> Document configuring NbTrans overrides

doc/content/the-things-stack/host/aws/ecs/best-practices/_index.md
Added a best practice for AWS RDS auto minor version upgrade option for the RDS database in TTS AWS ECS deployment.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/1050#issuecomment-2034823757
- Add a best practice specific to the AWS RDS Auto minor version upgrade option
@adriansmares, please review.
=> doc: Add best practice on AWS RDS auto minor version upgrade option

doc/content/the-things-stack/cloud/billing-and-subscription-management/_index.md
Add the error `VAT ID is not valid` to the [Subscription and Billing Management](https://www.thethingsindustries.com/docs/the-things-stack/cloud/billing-and-subscription-management/) documentation guide. 
**New FAQ:**
- Added a new FAQ about the error `VAT ID is not valid` to the [Subscription and Billing Management](https://www.thethingsindustries.com/docs/the-things-stack/cloud/billing-and-subscription-management/) documentation guide. 
...
=> doc: Add the `VAT ID is not valid` error

doc/content/the-things-stack/host/docker/upgrading/_index.md
Add the `noc-db` schema migration command to upgrade The Things Stack guide.
Ref: https://www.thethingsindustries.com/docs/the-things-stack/host/docker/upgrading/#migrations
- Added `noc-db` schema migration command.
...
=> doc: Add noc database schema migration command

doc/content/the-things-stack/migrating/gateway-migration.md
Added troubleshooting gateway reference with common errors under the migrating gateways section.
Ref: https://www.thethingsindustries.com/docs/the-things-stack/migrating/gateway-migration/
**Before:**
**After:**
- Added the troubleshooting gateways reference. Ref: https://www.thethingsindustries.com/docs/the-things-stack/migrating/gateway-migration/
...
=> doc: Minor addition of troubleshooting gateways reference

doc/content/the-things-stack/host/docker/troubleshooting.md
Add connection refused error to the troubleshooting installation guide.
Ref: https://www.thethingsindustries.com/docs/the-things-stack/host/docker/troubleshooting/
- Added the connection refused error with the resolution in troubleshooting TTS installation.
NA
=> doc: Add connection refused error to troubleshooting TTS installation

doc/content/integrations/cloud-integrations/thingsboard/_index.md, doc/content/integrations/webhooks/troubleshooting.md
Small fixup for recently merged PRs
=> doc: Minor fixes

doc/content/the-things-stack/cloud/billing-and-subscription-management/_index.md
=> doc: Payment overdue info

doc/content/devices/troubleshooting/_index.md
Add the `no downlink path available` error to the [Troubleshooting Devices](https://www.thethingsindustries.com/docs/devices/troubleshooting/) guide. 
**New:**
- Added a new sub-section about `no downlink path available` error to the [Troubleshooting Devices](https://www.thethingsindustries.com/docs/devices/troubleshooting/) guide. 
...
=> doc: Add the downlink path unavailable error with multicast devices

doc/content/devices/configuring-devices/multicast/index.md
Add the process of configuring MAC settings for a Multicast device.
**New:**
- Added a new section on `How to update the MAC Settings of a Multicast device?` to the [Multicast](https://www.thethingsindustries.com/docs/devices/configuring-devices/multicast/) guide. 
...
=> doc: MAC settings configuration process for Multicast devices

doc/config/_default/config.toml, doc/content/api/reference/grpc/application_webhooks.md, doc/content/api/reference/grpc/tenant.md, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_list.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_tenants_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_tenants_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_tenants_list.md, doc/content/ttn-lw-cli/ttn-lw-cli_tenants_search.md, doc/content/ttn-lw-cli/ttn-lw-cli_tenants_update.md, doc/content/ttn-lw-cli/ttn-lw-cli_users_bookmarks_list.md, doc/content/whats-new/3.30.1.md, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.ApplicationServer.Webhooks.Queue.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.ApplicationServer.Webhooks.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.ApplicationServer.yml, doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhook.yml, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhookQueue.yml, doc/data/api/ttn.lorawan.v3/messages/AsConfiguration.Webhooks.Queue.Retry.yml, doc/data/api/ttn.lorawan.v3/messages/AsConfiguration.Webhooks.Queue.yml, doc/data/api/ttn.lorawan.v3/messages/AsConfiguration.Webhooks.yml, doc/data/api/ttn.lorawan.v3/messages/ListUserBookmarksRequest.yml
Release v3.30.1 documentation.
- Added documentation for v3.30.1.
```
```
```
```
=> Release v3.30.1 documentation

doc/content/integrations/webhooks/queue.md, doc/content/the-things-stack/alerting/_index.md
Add note on alerting beta status.
- Add note on alerting beta status.
=> Add note on alerting beta status

doc/content/the-things-stack/cloud/billing-and-subscription-management/_index.md
Added a note on the device registration limit in The Things Stack Cloud tenant application.
Ref: https://www.thethingsindustries.com/docs/devices/adding-devices/
- Added note point on device registration limit in an application.
...
=> doc: Add devices registration limit in an application

doc/content/integrations/mqtt/_index.md
Add the `as.mqtt.connect.fail` event with error message `api key with id {api_key_id} not found` to the [Troubleshooting Devices](https://www.thethingsindustries.com/docs/devices/troubleshooting/) guide. 
**New:**
- Added a new sub-section about the error message `api key with id {api_key_id} not found` to the [Troubleshooting Devices](https://www.thethingsindustries.com/docs/devices/troubleshooting/) guide. 
...
=> doc: Add API key not found error with the MQTT events

doc/content/reference/rate-limiting/_index.md, doc/data/rate-limiting.yml
Documentation for https://github.com/TheThingsNetwork/lorawan-stack/pull/7119
The rate limiting key has changed.
=> Update rate limiting key for Basic Station LNS

doc/content/the-things-stack/cloud/_index.md
References https://github.com/TheThingsIndustries/infrastructure/issues/1062
- Add `as1` cluster to cluster table.
nil
=> doc: Add `as1` to the Clusters table

doc/content/the-things-stack/cloud/_index.md
Update TTSC cluster names
NA
- Add the city names where not available.
NA
=> Update TTSC cluster names

doc/content/integrations/cloud-integrations/azure-iot-hub/deployment.md, doc/package.json, doc/themes/the-things-stack/layouts/partials/head/head.html, doc/themes/the-things-stack/layouts/shortcodes/aws-deploy-cloudformation.html, doc/themes/the-things-stack/layouts/shortcodes/cli-downloader.html, doc/yarn.lock
Fix primary button on the Docs
- Update TTUI
- Use TTUI classes for the primary buttons
- Add margins
...
=> Quick fix for primary buttons in the Docs

doc/content/the-things-stack/host/aws/ecs/mutual-tls/_index.md
This clarifies the documentation around mTLS configuration and makes it align with some code changes per https://github.com/TheThingsIndustries/lorawan-stack/pull/4285.
- Removed config for per-tenant CA
- Small editorial changes
Should be merged with https://github.com/TheThingsIndustries/lorawan-stack/pull/4285
=> mTLS clarifications

doc/content/the-things-stack/migrating/migration-tool/export-from-firefly.md
Clarify Join EUI usage for Firefly migration
NA. This is a simple fix.
- Clarify Join EUI usage for Firefly migration
=> Clarify Join EUI usage for Firefly migration

doc/content/integrations/webhooks/retries.md, doc/content/the-things-stack/alerting/_index.md
Remove beta note on alerting and webhooks
NA this is one line change in two pages.
- Remove beta note on alerting and webhooks
=> Remove beta note on alerting and webhooks

doc/content/the-things-stack/host/kubernetes/azure/architecture/_index.md, doc/content/the-things-stack/host/kubernetes/generic/configuration/_index.md, doc/content/the-things-stack/host/kubernetes/generic/preparation/_index.md, doc/content/the-things-stack/host/kubernetes/generic/prerequisites/_index.md
References: https://github.com/TheThingsIndustries/lorawan-stack-k8s/pull/45
- Add description how to disable blob usage
...
=> Add description how to disable blob usage

doc/data/glossary.yml
=> doc: Glossary update

doc/content/concepts/features/cli/reference/_index.md
Fix CLI reference page that was accidentally left out in the restructure.
- Add a CLI Reference page.
NA
=> Fix CLI reference page

doc/config/_default/config.toml, doc/content/concepts/features/cli/_index.md, doc/content/sitemap/_index.md, doc/content/ttn-lw-cli/_index.md, doc/themes/the-things-stack/layouts/partials/footer/footer.html, doc/themes/the-things-stack/layouts/partials/sitemap-recursion.html, doc/themes/the-things-stack/layouts/shortcodes/sitemap.html
Introduce a human-readable sitemap to the documentation
Refs: https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1394#issuecomment-2618496120
- Add a new auto-generated sitemap partial.
- Add sitemap link to the footer.
- We already have a bot-readable `sitemap.xml` from Hugo. This is a separate page in Human readble format.
- The CLI Reference is a quick fix for a different reported issue.
=> Introduce a human-readable sitemap to the documentation

doc/config/_default/config.toml, doc/content/api/reference/grpc/application_server.md, doc/content/api/reference/grpc/network_server.md, doc/content/api/reference/grpc/storage_integration.md, doc/content/enterprise/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_storage_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_storage_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_tenants_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_users_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_users_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_users_list.md, doc/content/ttn-lw-cli/ttn-lw-cli_users_search.md, doc/content/ttn-lw-cli/ttn-lw-cli_users_set.md, doc/content/whats-new/3.33.0.md, doc/content/whats-new/3.33.1.md, doc/data/api/ttn.lorawan.v3/messages/ApplicationUplink.yml, doc/data/api/ttn.lorawan.v3/messages/LastBatteryPercentage.yml
Release 3.33.1 documentation.
- Added documentation for 3.33.1.
```
```
```
```
=> Release 3.33.1 documentation

doc/content/concepts/migration/exporting-end-devices/_index.md, doc/content/concepts/migration/exporting-end-devices/export-from-awsiot.md
References: https://github.com/TheThingsNetwork/lorawan-stack-migrate/issues/143
- Add migrating from AWS IoT section
...
=> Add migrating from AWS IoT section

doc/content/concepts/features/console/troubleshooting/_index.md
Add new doubt/error, regarding the time difference in Console Live event and device/application/gateway event details. This is to be added in [Console Troubleshooting Section](https://www.thethingsindustries.com/docs/concepts/features/console/troubleshooting/)
**New:**
Added new doubt/error regarding the time difference in Console live event(Local browser time) and device/application/gateway event details(UTC time).
...
=> doc: Add time difference in console troubleshooting

doc/content/concepts/advanced/user-management/troubleshooting/_index.md
Add new error `Must not contain user ID` in the user management troubleshooting [guide](https://www.thethingsindustries.com/docs/concepts/advanced/user-management/troubleshooting/).
<details><summary>Error details</summary>
<p>
```
{
"code": 3,
"message": "error:pkg/identityserver:password_contains_user_id (must not contain user ID)",
"details": [
{
"@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
"namespace": "pkg/identityserver",
"name": "password_contains_user_id",
"message_format": "must not contain user ID",
"correlation_id": "2529d49ee7854abd8012765a1cfc1c68",
"code": 3
}
]
}
```
</p>
</details> 
**New:**
Added new error `Must not contain user ID` in the user management troubleshooting guide. This error occurs when the password contains user id while creating user.
...
=> doc: Add new error Must not contain userID

doc/content/getting-started/3-try-starter-kit/activate/_index.md
Adding a link in the Starter Kit section to the YouTube video guide.
- Add youtube link under toggle
- Move paragraph
...
=> doc: Link starter kit doc to youtube video
