TheThingsIndustries/lorawan-stack-docs

doc/content/reference/root-certificates/_index.md
Add ISRG Root X1 and DST Root X3 as fallback certificates for devices that don't support concatenated .pems (Laird gateways don't, probably others too)
=> doc: Add ISRG and DST root certs

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, LICENSE, README.md
Proposal for license and contributing doc.
Do we need a changelog here? How do we release the docs?
I am for build and deploy automatically on any merges to master, and I suppose we manually update versions whenever a new lorawan-stack tag is released.
Hugo uses a `master` and `next` scheme for changes which will apply to future releases -> https://github.com/gohugoio/hugoDocs
They also recommend that pull requests include changes to both the code repo and the docs repo, but I don't know how that's possible
=> util: Add license and contributing

CONTRIBUTING.md, Makefile, README.md, doc/archetypes/section-bundle/_index.md
Turned the example doc in to an archetype so we can easily create new docs with `make new <path>`.
=> doc: Add archetype to easily create new docs

doc/content/getting-started/cli/installing-cli/_index.md
Adding notes for using CLI on Windows.
Using `ttn-lw-cli.exe`, defining auto-completion script as a .ps1 file, adding note for custom https port.
=> doc: Add notes for using CLI on Windows

doc/content/getting-started/migrating-from-networks/device-json.md, doc/content/getting-started/migrating-from-networks/import-devices.md, doc/content/getting-started/migrating-from-networks/migrate-from-chirpstack.md
Adding instructions for exporting devices from Chirpstack.
Ref: https://github.com/TheThingsIndustries/lorawan-stack/issues/2329
Tested `ttn-lw-migrate` tool according to [these instructions](https://github.com/TheThingsIndustries/lorawan-stack-migrate/blob/master/README.md) with local TTS and Chirpstack deployments.
=> doc: Add Chirpstack migration section to docs

doc/config/_default/config.toml
Fix old docs references in config
=> Fix old docs links in config

doc/content/integrations/payload-formatters/javascript.md
=> Add ES5 warning to payload formatter doc

CONTRIBUTING.md, doc/archetypes/section-bundle/_index.md
Define a standard for using variables which a user must replace in docs.
Also reordered/regrouped the style guidelines
Exporting the variable in to the environment helps because
- It's easy for the user to see the strings they need to replace (they're also highlighted red in code)
- All variables can be moved to the top of the sequence of commands, and the user only need export once
=> util: Add user variables section to contributing

CODEOWNERS
This PR adds @pierrephz as codeowner for the theme and style folders of the docs hugo theme.
- Add Pierre as codeowner
As a designer, @pierrephz should sign off or propose changes to styling changes too
=> Add @pierrephz as style/theme codeowner

doc/archetypes/section-bundle/_index.md, doc/content/integrations/storage/_index.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/federated-auth/_index.md, doc/themes/the-things-stack/assets/css/theme.scss, doc/themes/the-things-stack/layouts/_default/list.html, doc/themes/the-things-stack/layouts/_default/single.html, doc/themes/the-things-stack/layouts/partials/new-in-version.html, doc/themes/the-things-stack/layouts/partials/pages-cards.html, doc/themes/the-things-stack/layouts/shortcodes/new-in-version.html
Closes #70 
Add Front Matter to mark entire sections as "New in Version."
Looks like:
And automatically marks the title on the content page:
Only problem is that it sometimes wraps
Currently styled exactly like inline distributions (distributions styling will change soon with logos)
@pierrephz @kschiffer any quick feedback?
- Add Front Matter
- Add documentation
- Clean up existing tags
=> Create new_in_version Front Matter

doc/data/glossary.yml
Small update on the text about LoRaWAN versions
- Explaining v1.0.2 and v1.0.3 are most commonly used.
=> doc: Update glossary with info on LoRaWAN versions

doc/content/getting-started/installation/configuration/_index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/running-the-stack.md
Add `tenancy` configuration to example `ttn-lw-stack-docker-enterprise` configuration file.
Without this, multi-tenancy doesn't work right as `base-domain` does not match instance url.
=> doc: Add tenancy config to enterprise config file

doc/content/integrations/storage/configuration.md
Configuration for storage integration should be Enterprise only. Cloud is automatically configured.
=> Mark storage config as enterprise only

doc/config/_default/config.toml, doc/content/reference/api/authentication.md, doc/content/reference/api/gateway_server_mqtt.md, doc/layouts/shortcodes/repo-file-url.html, doc/layouts/shortcodes/repo.html, doc/layouts/shortcodes/tts-repo-file-url.html
Closes #113
- Deleted unused `repo` shortcode
- Renamed `repo-file-url` to `tts-repo-file-url` and make it link to current minor branch of https://github.com/TheThingsNetwork/lorawan-stack.
- Fixed documentation pages that linked to `default` branch
=> doc: Fix links to files in lorawan-stack repository

.github/PULL_REQUEST_TEMPLATE.md
Kevin raised a good point that we often don't consider how our rendered Markdown will look -> https://discuss.thethingsindustries.com/t/how-to-improve-images-on-the-documentation-page/387/2?u=benolayinka
This PR adds a check to post a screenshot in the PR template, to encourage contributors to build and preview their work.
=> Add screenshot req to PR template

doc/content/getting-started/aws/ecs/database-operations/_index.md
When I was deploying the stack on ECS, I had some trouble. Most of it came from not reading the docs, but there could be more information regarding initialization. This PR aims at fixing the problem.
Improve documentation of initializing ECS deployment.
=> doc: Improve documentation of stack init

Makefile, doc/themes/the-things-stack/assets/css/theme.scss, doc/themes/the-things-stack/assets/js/theme.js, doc/themes/the-things-stack/layouts/partials/nav.html
Migration to thethingsindustries.com/docs
1. Add a banner informing of the change
2. Change `HUGO_BASE_URL` for links on the page
3. Add a JS function that redirects users to `thethingsindustries.com/docs` if they see the webpage from somewhere else. Same pattern is on docs for thethingsnetwork.org.
The biggest difficulty is coordinating changes in a few places so that people wouldn't experience downtime. Therefore the plan is as follows:
1. Deploy to thethingsindustries.com a change that makes /docs connect to github pages (already on preview)
2. Merge this PR
3. Make thethingsstack.io redirect to thethingsindustries.com/docs (so that search engines won't be confused)
One important detail: we do NOT inform github itself about our change. That is, the `CNAME` file will keep pointing to …
=> util: Migration to thethingsindustries.com/docs

doc/content/gateways/semtech-udp-packet-forwarder/_index.md
Remove global_conf bug warning
=> doc: Remove global_conf warning from docs

CONTRIBUTING.md, doc/archetypes/section-bundle/_index.md, doc/content/getting-started/installation/configuration/_index.md, doc/content/integrations/aws-iot/_index.md, doc/content/reference/configuration/application-server.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/configuration/network-server.md, doc/content/reference/configuration/the-things-stack.md
Fixes #139 until we find a better solution
- Add CONTRIBUTING note about manually fixing headings with inline shortcodes
- Fix existing headings with inline shortcodes
=> Quickfix for inline shortcodes breaking headings

doc/themes/the-things-stack/layouts/_default/list.html, doc/themes/the-things-stack/layouts/_default/single.html, doc/themes/the-things-stack/layouts/partials/distributions.html, doc/themes/the-things-stack/layouts/shortcodes/distributions-inline.html, doc/themes/the-things-stack/layouts/shortcodes/distributions.html
Replace hardcoded link with hugo ref to downloads page (it broke when docs went to thethingsindustries.com/docs)
=> doc: Fix broken download link

doc/content/devices/device-claiming/_index.md
Corrected the link on how to claim a device in the Device Claiming section.
Ref: https://www.thethingsindustries.com/docs/devices/device-claiming/
=> doc: Corrected the link on device claiming

doc/content/getting-started/events/_index.md
Quickfix PR, add `Accept: text/event-stream` header to example curl command for streaming events.
=> Add "Accept: text/event-stream" header to events API example curl command

doc/themes/the-things-stack/layouts/shortcodes/proto/message.html
This fixes rendering of key-value validation rules, which were previously not rendered.
Refs https://github.com/TheThingsIndustries/lorawan-stack-support/issues/263
=> Fix rendering of key-value rules in API reference

doc/themes/the-things-stack/assets/css/theme.scss, doc/themes/the-things-stack/layouts/shortcodes/proto/message.html
Closes #90 
Long name and type fields break the message table layout. Proposing breaking out the fields to individual tables, which wastes horizontal space but is the best way I can think of to accomodate for unknown length entries. One issue with this layout is that it's not quite as clear that the fields are all sibling subfields of the same message. If anyone has an idea for making that more semantically clear, suggest it. Maybe something like a vertical line joining the fields.
Before:
After:
=> util: Change message proto layout

doc/content/getting-started/migrating/_index.md, doc/content/getting-started/migrating/device-json.md, doc/content/getting-started/migrating/gateway-migration.md, doc/content/getting-started/migrating/major-changes.md, doc/content/getting-started/migrating/migrate-from-chirpstack.md, doc/content/getting-started/migrating/migrating-from-v2.md
Update documentation to use [ttn-lw-migrate](https://github.com/TheThingsNetwork/lorawan-stack-migrate) instead of `ttnctl` for migrating from v2 to v3.
=> Document using ttn-lw-migrate to migrate from v2

doc/content/devices/mac-settings/_index.md
- Added `<application_id>` flag in "Configure Factory Preset Frequencies" command for ABP Devices
- Added `=` in the CLI command  to enable/disable ADR
Ref: https://www.thethingsindustries.com/docs/devices/mac-settings/
=> doc: Fix example commands of Preset Frequencies & ADR

doc/content/devices/downlink-queue-ops/_index.md
Added `--f-port` flag in the example CLI command to replace the existing downlink queue with a new item.
=> doc: Add f-port flag to example command in downlink-queue-ops

doc/content/reference/configuration/identity-server.md
This adds the configuration reference for the `is.user-registration.enabled` option added in https://github.com/TheThingsNetwork/lorawan-stack/pull/3676.
This is blocked on https://github.com/TheThingsNetwork/lorawan-stack/pull/3676 and after that the v3.11 release.
=> Add reference for is.user-registration.enabled config option

doc/content/devices/abp-vs-otaa/_index.md
Adding a section dedicated to accenting why OTAA is recommended and not ABP.
Closes #215 
More info from the team is warmly welcome
=> doc: Add ABP vs OTAA doc

doc/config/_default/config.toml
Lack of sitemap was breaking search at tti.com/docs. This closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/240
@htdvisser , was sitemap generation disabled on purpose?
=> util: Enable docs sitemap

doc/content/getting-started/migrating/device-json.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/243
@neoaggelos @laurensslats why in the OTAA migration example is the `Rx1 Delay` set as `mac-settings.rx1-delay.value` instead of `mac-settings.rx1-delay` ?
=> doc: Add instruction for Rx1 on migrated devices

doc/content/integrations/aws-iot/default/architecture.md, doc/content/integrations/aws-iot/default/deployment-guide.md
Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/235
Updated `The Things Join Server` to `Join server` as both the in-cluster Join server in Cloud Hosted & also The Things Join Server supports this feature.
=> Update aws integration end-to-end-encryption section

doc/assets/css/common/variables.scss, doc/assets/css/sidebar/sidebar.scss, doc/content/getting-started/installation/configuration/index.md, doc/layouts/_default/baseof.html
This makes the rendered content wider.
I found it increasingly annoying to read things as the content was fixed to max 1344px. I have a 4K screen to use more effective screen space and avoid dense content, but our docs doesn't let me do that.
Here's what it looks like **before**:
And **after**:
Change the default max that Bulma uses from 1344 to 1920px, and the other widths accordingly with the same factor. The widths are still divisible by 12 and 16 for the grid system (that we don't seem to use really).
=> Make container wider

doc/content/getting-started/cli/installing-cli/_index.md
Fix for https://www.thethingsnetwork.org/forum/t/ttn-cli-au1-v3-cluster-ttn-lw-cli-login-loads-to-blank-webpage-the-things-stack/45403
@htdvisser
=> doc: Add CLI note about au1 IS

doc/content/gateways/semtech-udp-packet-forwarder/_index.md
Adding a note about inconsistency of using the term `gateway ID` in the Console and in the `global_conf.json` file. 
Ref: https://github.com/TheThingsNetwork/lorawan-stack/issues/3777
=> doc: Note about gateway ID inconsistency

doc/content/getting-started/migrating/major-changes.md
Document changes in MAC command handling
- Add a note that The Things Stack expects the end device to always comply with the LoRaWAN spec.
- Document how to disable NS sending `DevStatusReq` commands periodically. 
@rvolosatovs Any other changes that are important to document?
=> Document changes in MAC command handling from V2

doc/content/getting-started/migrating/migrating-from-v2.md
Added a note in the `Migrating from The Things Network Stack V2` document related to the `device ID` constraint comparing `TTI V2` to `TTS V3` and how the migration tool solves this.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/262
...
...
=> Add note about dev_id constraints in TTS V3

doc/content/gateways/semtech-udp-packet-forwarder/_index.md, doc/content/getting-started/aws/ecs/deployment/_index.md, doc/content/getting-started/migrating/import-devices.md, doc/content/integrations/adding-applications/_index.md, doc/content/integrations/aws-iot/default/architecture.md, doc/content/integrations/aws-iot/default/deployment-guide.md, doc/content/integrations/pubsub/_index.md, doc/content/integrations/storage/_index.md, doc/content/integrations/storage/enable.md, doc/content/integrations/webhooks/webhook-templates/format.md, doc/content/reference/components/application-server.md, doc/content/reference/configuration/application-server.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/configuration/the-things-stack.md, doc/content/reference/federated-auth/_index.md
Closes #310
Should sections that have been marked as removed in certain version be completely removed from the documentation? Example: application linking -> https://www.thethingsindustries.com/docs/integrations/adding-applications/
Should I leave **Deprecated in version xxx** sections untouched? What does deprecated mean here, that it will be removed in the next version?
=> doc: Remove old new-in-version tags, small fixes

doc/assets/css/sidebar/sidebar.scss
Some pages currently overflow the column, pushing the nav to the side. See https://www.thethingsindustries.com/docs/devices/mac-settings/
and the underlying bug in Bulma - https://github.com/jgthms/bulma/issues/1540
This PR fixes that
Before:
After:
=> doc: Fix content overflow

doc/assets/css/common/global.scss, doc/layouts/_default/list.html, doc/layouts/_default/single.html, doc/layouts/partials/header-hash.html, doc/layouts/partials/sidebar/headers.html
Closes #278 #174 
This PR fixes unescaped characters in the TOC and adds a hash to headers to allow easy copy and pasting of the anchor URL
=> Fix headers and add anchor links

doc/assets/css/common/variables.scss, doc/assets/css/header/nav.scss
This quickfix fixes selected content being not visible behind the navbar e.g. for glossary items. This happened when linking glossary items directly e.g. as the Console does.
Add CSS to add an offset to selected anchor links.
=> Fix anchor link navbar offset

.github/ISSUE_TEMPLATE/release.md
These are just small text fixes for the release template I thought were needed. 
The link I changed led to 404 error, and I changed the path to match the previous text in the template.
=> doc: Updating the release template

doc/content/reference/branding/_index.md, doc/content/reference/configuration/console.md, doc/content/reference/configuration/identity-server.md
This PR adds documentation for the recently added deployment information configs, which are shown in the headers of the web UI.
- Extend config reference for the console
- Extend config reference for the IS
- Extend the branding guide
=> Add documentation for new deployment information configs

doc/content/devices/abp-vs-otaa/_index.md
Add a paragraph explaining why we used ABP in the past for a small number of cases. Also explain why this is not necessary and why we can and should use OTAA.
This follows after a discussion on the forum: https://www.thethingsnetwork.org/forum/t/how-to-migrate-abp-devices-from-v2-to-v3/43705/73
...
- ...
- ...
...
=> docs: Why was ABP used before

doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-open-source.yml
This is a small Pull Request that fixes the example configuration.
- The GCS API endpoint was missing
- The public MQTT addresses contained `https://`
=> Fix example configuration

doc/assets/css/header/nav.scss, doc/assets/js/theme.js, doc/layouts/partials/header/nav.html
Removes the migration banner, effectively reversal of https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/152
Removed the migration banner
=> doc: Remove migration banner

doc/content/download.html, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/_index.md
Adding a note for setting environmental variables using Windows PowerShell, because it's different compared to using Command Prompt. This can be misleading, because people might not notice that using the `set` command in PowerShell doesn't actually set the variable, since it also doesn't report any error (or anything at all). As a consequence, migration tool can't export the device from V2.
+ changed "The Things Network" to "Community Edition" on Downloads page which is closing #298
=> doc: Add note for PowerShell

doc/content/getting-started/aws/ecs/monitoring/_index.md, doc/content/reference/telemetry/_index.md
This pull request updates the name of the log messages metric (while mentioning the old name)
Refs https://github.com/TheThingsNetwork/lorawan-stack/issues/4118 https://github.com/TheThingsNetwork/lorawan-stack/pull/4226
=> Rename log messages metric for v3.13.1

doc/assets/css/common/global.scss, doc/layouts/shortcodes/proto/enum.html, doc/layouts/shortcodes/proto/message.html, doc/layouts/shortcodes/proto/method.html
Closes #371 
- Add border between tables
- Remove borders inside tables
- Right align headers
=> Update API doc styling

doc/layouts/_default/list.html, doc/layouts/_default/single.html, doc/layouts/whats-new/list.html, doc/layouts/whats-new/single.html
Switch to 12-grid system and set fixed width on middle column to prevent overflow (see https://www.thethingsindustries.com/docs/getting-started/installation/configuration/ for example of overflow with horizontal scrolling)
=> doc: Set fixed width middle column

CODEOWNERS
Quickfix to remove me as codeowner of the hugo package.
- Remove me as codeowner of the hugo package
Unfortunately, I don't have time to codeown this anymore and I think me being listed there only drags everything
=> Remove @kschiffer from Hugo codeowners

doc/content/integrations/adding-integrations/_index.md
The "Integrations with MQTT Clients" link is not working on this page: https://www.thethingsindustries.com/docs/integrations/adding-integrations/
I'm not certain, but believe that this will fix it. The double parenthesis seem like the only difference from the other links on this page and would explain why the redirect is breaking.
...
...
- Remove extra set of parenthesis from link definition.
- ...
...
=> doc: Fix link to Integrations with MQTT Clients.

doc/content/integrations/cloud-integrations/aws-iot/default/architecture.md
Closes #378 
Added a note that scheduling downlinks from TTS is restricted in case when end-to-end encryption option is enabled on AWS
=> doc: Add note about scheduling downlinks

.github/ISSUE_TEMPLATE/release.md, doc/content/whats-new/3.10.6.md, doc/content/whats-new/3.10.7.md, doc/content/whats-new/3.10.8.md, doc/content/whats-new/3.11.0.md, doc/content/whats-new/3.11.1.md, doc/content/whats-new/3.11.2.md, doc/content/whats-new/3.11.3.md, doc/content/whats-new/3.12.2.md, doc/content/whats-new/3.13.0.md, doc/content/whats-new/3.13.1.md
Removing empty sections from _What's new in version_ files, to make files consistent.
=> doc: Remove empty sections from What's new in version files

doc/content/getting-started/migrating/gateway-migration.md, doc/content/getting-started/migrating/migrating-from-v2/_index.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-console.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md, doc/content/getting-started/migrating/migrating-from-v2/packet-broker-requirements.md
Closes #369 and #368 + some minor updates
Added the information that gateways can be migrated to The Things Stack Community Edition while still providing uplink and downlink coverage for The Things Network V2, that TTIGs cannot be migrated atm, how to reuse payload (de)coders from V2
=> doc: Document V3 -> V2 routing, reusing payload (de)coders, TTIG migration

doc/themes/the-things-stack/assets/css/header/nav.scss
Move the search to the dropdown menu on really small screens
=> doc: Add search breakpoint for small screens

doc/content/reference/data-formats/_index.md
uplink_message.rx_metadata.snr is documented as 5 (integer) but is a double (5.2).
Changed to double format to indicated correct type.
none
=> doc: Clarify type of uplink_message.rx_metadata.snr

doc/content/integrations/storage/_index.md
Added a note in the storage integration guide to indicate that the TTS Cloud only stores uplink messages.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/246
...
- Added a note in the storage integration document
...
=> doc: Add note in storage integration for The Things Stack Cloud (#30)

.github/ISSUE_TEMPLATE/release.md
This prepares the release checklist for changes coming to v3.14.
V3.14 will use new proto generators. The Hugo data generator will then also work on arm64 (cc: @benolayinka), but the output is also going to be a bit different. To Hugo it should all look the same, but instead of having huge `enums.yaml`, `messages.yaml` and `services.yaml` files, it will now generate files for each enum, message and service individually.
This pull request updates the instructions in the release template so that those files will get synced correctly to the data dir.
=> Prepare release checklist for v3.14

doc/content/devices/best-practices/_index.md
Adding 2 points to the Device Best Practices:
1. Support force rejoin command or downlink
2. LoRaWAN Certified
- 2 points, with descriptions added.
=> doc: Additions to LoRaWAN Best Practices

doc/content/gateways/thethingsindoorgateway/_index.md
Issue #462
5BA0CB should be 58A0CB in 2 places.
...
...
- ...
- ...
...
=> Fix typo in TTIG gateway doc

doc/data/glossary.yml
Reference links in the Glossary documentation pointing to the LoRa Alliance website are broken probably due to the changes in the LoRa Alliance website.
1. Updated the broken links in the Glossary section with the working ones.
2. Updated the example URL in the `Tenant ID` description to make it more clear.
=> doc: Fix broken links in Glossary documentation

doc/content/getting-started/aws/ecs/deployment/_index.md
`4-2-configuration` is called `4-2a-configuration` ever since rate limiting has been introduced
Renamed `4-2-configuration` to `4-2a-configuration`
=> doc: Rename the configuration template

doc/content/getting-started/api/_index.md, doc/content/reference/api/_index.md, doc/content/reference/api/application.md, doc/content/reference/api/end_device.md, doc/content/reference/api/events.md, doc/content/reference/api/field-mask.md, doc/content/reference/api/gateway.md, doc/content/reference/api/gateway_server.md, doc/content/reference/api/organization.md, doc/content/reference/api/storage_integration.md, doc/content/reference/api/user.md, doc/themes/the-things-stack/layouts/shortcodes/proto/message.html
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/373
Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/527
- Add missing messages and enums to API docs
- Properly describe field mask usage, add warnings
- Add that identifiers in body are not required if they are specified in url
=> Improve description of field masks in API documentation

doc/content/gateways/troubleshooting/_index.md
Closing https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/544
We already have this point in Troubleshooting and I think the existing documentation is enough, but the fact that the gateway can be registered in some other tenant isn't stated, so this PR is just adding that line.
=> doc: Add a note about already registered in other tenant

doc/content/getting-started/aws/ecs/updating/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/512
TimescaleDB update now doesn't require restart of ApplicationServer
=> Timescale db upgrade

doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md
Closes #481 
Fixing and re-positioning notes on using the `--ttnv2.resets-to-frequency-plan` migration tool flag.
=> doc: Fix migration tool flag-related notes

doc/themes/the-things-stack/assets/css/common/global.scss
Closes #635
Before:
After:
Added this as described in https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/archetypes/section-bundle/_index.md#tables
=> doc: Add custom css class for LBS XTime table

doc/content/integrations/cloud-integrations/aws-iot/application-server-telemetry/_index.md, doc/content/integrations/cloud-integrations/ubidots/_index.md, doc/content/integrations/mqtt/_index.md, doc/content/reference/data-formats/_index.md
Remove data_rate_index from uplink message examples. Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/4869
- Remove `data_rate_index` from examples.
=> Remove data_rate_index from uplink message examples

doc/content/reference/configuration/the-things-stack.md, doc/content/reference/networking/_index.md
https://github.com/TheThingsNetwork/lorawan-stack/pull/4979
Added information about 1886 non-TLS interop port
=> doc: Add information about non-TLS interop port

doc/content/getting-started/migrating/faq.md, doc/content/getting-started/migrating/gateway-migration.md, doc/content/getting-started/migrating/migrating-from-v2/_index.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-console.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/_index.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md, doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md, doc/content/getting-started/migrating/migrating-from-v2/packet-broker-requirements.md, doc/content/reference/pb-routing/_index.md
Closes #671 
I removed all info related to TTN V2 from migration docs, left only what's relevant for TTI V2 (private instances).
=> doc: Update migration docs post TTN V2 shutdown

doc/content/integrations/webhooks/webhook-templates/instantiation.md
When [this](https://github.com/TheThingsNetwork/lorawan-stack/issues/5036) is fixed, one will be able to define the `fields` list of objects as empty using `fields:` or `fields: []`.
I reorganized the section a bit in order to separate the instructions on instantiating fields, headers and paths. I also added info that headers can be defines as empty using `headers:`
=> doc: Add info about creating empty headers and fields

doc/content/integrations/mqtt/mqtt-clients/eclipse-paho/_index.md
Add `auth=...` to fix broken publish example.
=> doc: Fix publish example

doc/content/gateways/thethingsindoorgateway/_index.md, doc/content/integrations/cloud-integrations/aws-iot/default/_index.md, doc/content/integrations/cloud-integrations/aws-iot/default/messages.md, doc/content/reference/configuration/network-server.md
Remove old `new-in-version` tags
=> Remove excessive `new-in-version` tags

doc/content/reference/rate-limiting/_index.md
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/5080
From the discussion in the issue, it seems adequate to have a reference that would introduce the behaviour of the algorithm used to whoever is trying to use rate limiting, it might facilitate the understanding of what's happening behind the curtains.
- Add sentence that points to a wikipedia explanation of the generic cell rate algorithm
I opted to leave the reference as its own sentence, since it starts with `For more details...` i imagine that only people interested in how it was implemented will click it.
=> doc: Add algorithm reference to rate limiting

doc/content/reference/configuration/cli.md
References https://github.com/TheThingsNetwork/lorawan-stack/issues/4902
References https://github.com/TheThingsNetwork/lorawan-stack/pull/5121
- Add retry options to the CLI configuration reference
The `CONTRIBUTING.md` specifies:
>Use the {{< new-in-version "3.8.5" >}} shortcode to tag documentation for features added in a particular version. For documentation that targets `master`, that's the next patch bump, e.g 3.8.x. For documentation targeting `develop` that's the next minor bump, e.g 3.x.0.
But the branch `develop` doesn't seem to exist anymore. On another note, the `{{< new-in-version "3.8.5" >}}` doesn't really match other examples in the configuration reference, so for now I'm leaving it out of the cli-retry section.
=> doc: Add retry options to cli configuration

doc/content/getting-started/api/_index.md, doc/content/reference/api/application.md, doc/content/reference/api/client.md, doc/content/reference/api/gateway.md, doc/content/reference/api/organization.md, doc/content/reference/api/user.md, doc/content/reference/purge/_index.md
- Added some missing API entries (ones I spotted while adding entries for purge)
- Cross-linked sections "Purge Entities" and "Using the API -> Purge Entities"
=> Document purging entities via API

doc/content/gateways/troubleshooting/_index.md
Closes #712 
I see that the [reference](https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT#L299) contains less info than what we have on docs page, and someone actually provided the info that we have on docs page before, so I combined something but I'm not sure if I'm interpreting this correctly. If this is not correct, please explain what causes the data pull failure
=> doc: Fix troubleshooting downlinks

doc/content/getting-started/aws/ami/application-server-telemetry/_index.md, doc/content/getting-started/aws/ami/best-practices/_index.md, doc/content/getting-started/aws/ami/troubleshooting/_index.md, doc/content/getting-started/aws/ecs/best-practices/_index.md, doc/content/getting-started/aws/ecs/deployment/_index.md, doc/content/getting-started/aws/ecs/interop/_index.md, doc/content/getting-started/aws/ecs/troubleshooting/_index.md, doc/content/getting-started/aws/ecs/updating/_index.md
https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/815
1. Reorder sections in AMI and ECS deployments
2. Remove `application-server-telemetry` section (deprecated in 3.11.1)
3. In ECS deployment:
- replace "3.x" with "3.x.y"
- move TimescaleDB template information so that templates are ordered correctly
- add information about rate limiting template
- add information in `1-1` about requesting Let's Encrypt certificates in `5-7`
- remove `5-3d-ecs-gcs-service` template information
=> doc: Small updates

doc/content/devices/best-practices/_index.md, doc/content/devices/class-b/index.md, doc/content/devices/class-c/_index.md, doc/content/devices/troubleshooting/_index.md, doc/content/gateways/lora-basics-station/_index.md, doc/content/gateways/thethingsindoorgateway/_index.md, doc/content/gateways/troubleshooting/_index.md, doc/content/reference/api/gateway_server_mqtt.md, doc/content/reference/packet-forwarder/_index.md
Closes #801 and #800.
Rearranging [Troubleshooting Gateways](https://www.thethingsindustries.com/docs/gateways/troubleshooting/) doc to have a more natural reading flow, spelling and link fixes, removing unnecessary bold text style, etc.
=> doc: Update troubleshooting, spelling and link fixes

doc/content/gateways/thethingsindoorgateway/_index.md
=> doc: Add note about auth check for local TTS server

doc/content/getting-started/migrating/import-devices.md
Fix a bad link for CSV file reference
=> doc: Fix CSV reference link

doc/content/getting-started/aws/ami/deployment-guide/_index.md, doc/content/getting-started/aws/ami/post-deployment/_index.md, doc/content/getting-started/aws/ami/updating/_index.md, doc/content/getting-started/aws/ecs/monitoring/_index.md, doc/content/getting-started/cloud-hosted/_index.md
Follow up on https://github.com/TheThingsIndustries/lorawan-stack/pull/3156
Use The Things Stack Enterprise, almost everywhere via the shortcode. If that isn't possible, because it's a literal block, spell it out.
The AMI CFT parameter `InstanceName` that defaults to `the-things-enterprise-stack` cannot be changed as it would trigger a resource replacement in AWS. This is already reflected in `lorawan-stack-aws` repo.
=> Use name The Things Stack Enterprise

doc/content/reference/spec-regional-parameters/index.md
Closes #809 
Add info that TTS supports RP002 spec and modify specification names to reflect names in lists for LoRaWAN version and Regional Parameters version in the Console.
=> doc: Add RP002 info, modify specification names

doc/content/getting-started/installation/configuration/index.md, doc/content/reference/configuration/identity-server.md, doc/content/reference/email-templates/_index.md, doc/content/reference/email-templates/available.md, doc/content/reference/email-templates/overriding.md, doc/themes/the-things-stack/layouts/_default/list.html, doc/themes/the-things-stack/layouts/_default/single.html, doc/themes/the-things-stack/layouts/partials/pages-cards.html, doc/themes/the-things-stack/layouts/partials/removed-in-version.html
This marks email template customization as "removed" and adds the `dir` email provider.
Refs https://github.com/TheThingsNetwork/lorawan-stack/pull/5406
n/a
- Fixed `removed-in-version` shortcode
- Removed email template stuff
- Added `dir` email provider
~Not sure what our current practice is for deleting pages. If instead of deleting pages, we want to update them with a message, then I can do that too.~
=> Remove references to customizable email templates

doc/config/_default/config.toml
As suggested in #documentation channel on Slack, I'm changing the "Get The Things Stack" button to lead to purchasing page instead of deployment options page
Needs a review because I wasn't sure if something else needs to be changed besides this link
=> doc: Point link to purchasing page

doc/content/getting-started/installation/balena/index.md
We have upgraded and cleaned up the different projects in the Balena Hub. Previous links were correctly redirecting to existing projects but with these changes it makes more sense (deploying TTS only, deploying BasicStation or deploying everything together).
Upgrades links to Balena Hub project deploying TTS (and related ones).
N/A
Changes to links to the already existing TTS project for Balena, as well as BasicStation project and the Standalone Gateway that includes BasicStation, TTS, NodeRED, InfluxDB and Grafana.
I'm the maintainer of the projects originally linked, this is just an update.
N/A
=> Update links in the Balena page

doc/content/devices/troubleshooting/_index.md
=> doc: Add troubleshooting entry

doc/content/reference/api/field-mask.md
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/5553
Add a note to documentation that updating ID fields via API is forbidden
=> doc: Add note about updating IDs via API

doc/content/getting-started/migrating/device-csv.md
Documentation for the new fields added to the csv converter. 
Added by https://github.com/TheThingsNetwork/lorawan-stack/pull/5582
- Added a few more fields to the csv table.
Tried to leave the order of the fields as similar as possible to the [JSON](https://www.thethingsindustries.com/docs/getting-started/migrating/device-json/#json-end-device-format) page.
=> doc: Add description for new csv fields on migration procedure

doc/content/getting-started/events/_index.md
Closes #827 
I observed a verbose stream of events in the Console of a locally deployed TTS Open Source instance, where I had 1 gateway and 1 device connected. I included some events that weren't included before in this example:
- `ns.up.join.receive`
- `ns.up.join.cluster.attempt`
- `ns.up.join.process`
- `ns.down.join.schedule.attempt`
- `gs.down.schedule.attempt`
- `ns.down.join.schedule.success`
- `ns.up.join.accept.forward`
I tried to understand the process of communication between TTS components based on the events dump from the Console, descriptions of these events in our documentation and some resources online, but haven't been able to understand it 100% and I think it might have something to do with the fact that some events might be arriving late in the Console. For example, …
=> doc: Update join flow

CONTRIBUTING.md, doc/data/frequency-plans.yml
Following up on an email from Yoshida Hidetoshi (TTN Japan) to add missing Japanese frequency plans to documentation.
I compared frequency plans available in TTS Console, the ones available in [frequency plans repo](https://github.com/TheThingsNetwork/lorawan-frequency-plans) and the ones described in the [documentation](https://www.thethingsindustries.com/docs/reference/frequency-plans/). In this PR, I'm adding those for Japan and one plan for China that I saw was missing.
I'm a bit lost because there's so many similar labels and I'm not sure if I'm interpreting info from frequency plans repository correctly (e.g. I'm not sure how to obtain a base frequency, so I just put there the minimum frequency that's indicated in the .yml file), so any suggestions or additional useful references …
=> doc: Add frequency plans for Japan

doc/content/reference/interop-repository/_index.md, doc/themes/the-things-stack/assets/css/common/variables.scss
Documentation for https://github.com/TheThingsNetwork/lorawan-stack/pull/5606
- Documents use of component selectors, including an example for The Things Join Server
- Removes some documentation bloat
This also makes the content wider; wasting horizontal space keeps on annoying me; I don't need CSS overrides to decide what the best content width is for me.
=> Document interop config component selectors

doc/content/getting-started/installation/certificates.md, doc/content/getting-started/installation/configuration/index.md
Closes #956 
Fixing references to sections from `ttn-lw-stack.yml` and `docker-compose.yml` that were slightly messed up by changing these files.
=> doc: Fix configuration references in code blocks

doc/content/getting-started/cli/troubleshooting.md
=> doc: Documents unauthenticated CLI error

doc/themes/the-things-stack/layouts/partials/distribution-icons.html
Fix a bad link (https://www.thethingsindustries.com/docs/download) to which clicking on a distribution type icon leads to. 
Set this link to https://www.thethingsindustries.com/docs/getting-started/what-is-tts/#the-things-stack-deployments, so that a user can see which deployment icon is related to.
=> doc: Fix distribution icons link

doc/themes/the-things-stack/assets/css/common/variables.scss, doc/themes/the-things-stack/assets/css/vendor/bulma/sass/base/generic.sass
Closes #1004 
- Change default colour of inline code blocks to black while keeping the blue colour when hyperlinked
Check out the screenshot. It contains both standard and hyperlinked inline code blocks
=> Differentiate between links and inline code snippets

doc/content/getting-started/console/troubleshooting/_index.md
=> doc: Document token refresh refused err

doc/content/getting-started/installation/configuration/index.md, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-custom-certificates.yml, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-open-source.yml
References https://github.com/TheThingsIndustries/lorawan-stack/pull/3589
This PR adds the NOC API Console configuration and fixes some line references in the configuration guide.
Old TLS fragment:
New:
Old Let's Encrypt:
New:
New component URIs:
Old OAuth client secret reference:
New:
Old NOC OAuth client secret reference:
New:
Old NOC Grafana reference:
New:
Old multi tenancy:
New:
- Add the `noc` section to the appropriate configs.
- Adjust, and fix, some references to the configuration files in order for the referenced lines to actually make sense.
- Format the configuration files.
=> Add NOC API references and fix line quotes

doc/content/getting-started/aws/ecs/deployment/_index.md
Closes #1064 
I cannot access templates on https://thethingsindustries.s3.amazonaws.com, can you please provide a link to the template? Do we need more info about the template?
=> doc: Add mtls to the list of ECS deployment templates

doc/themes/the-things-stack/layouts/index.html
Fix cards being cutoff on smaller screen sizes by enabling flex wrapping.
Before 
After
- Add `flex-wrap: wrap`
There may be a way to do this with bulma css, but I could not see anything at first glance.
=> Quickfix homepage cards styling

doc/content/getting-started/lorawan-basics/_index.md
During the restructuring, some unnecessary text has been migrated from The Things Network Learn section to The Things Stack - Getting Started - LoRaWAN page. There is also some technically incorrect information included on this page.
Related to: Issues in Getting Started - LoRaWAN page #1086
- ...
- ...
@nejraselimovic
=> doc: Fix getting started LoRaWAN

doc/content/the-things-stack/host/docker/certificates.md, doc/content/the-things-stack/host/docker/proxy.md
Add notes on using an external proxy. Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/1760
- Add notes on using an external proxy
=> Add notes on using an external proxy

doc/content/the-things-stack/concepts/server-addresses/_index.md
Refer to the issue 'Improve the page 'Server Addresses' to easily find the server addresses' https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1147
- Added tenant id and cluster id selector to dynamically change the server addresses.
- ...
@nejraselimovic
=> doc: Add tenant and cluster selector to the Server Addresses page

doc/content/gateways/models/tektelickonamicro/_index.md
Refer to issue Broken URLs on the 'Tektelic Kona Micro IoT LoRaWAN Gateway' page #1167
...
- Fix all the broken URLs
- Edit some text
@nejraselimovic
=> doc: Fix Broken URLs on the 'Tektelic Kona Micro IoT LoRaWAN Gateway' page

doc/content/the-things-stack/host/join-server/_index.md
Closes #1166 
I'm not sure if I understood this correctly so I'm also not sure if this PR covers the issue.. So my question - when a user uses TTJS, there is a pool of JoinEUIs (mentioned in PR), which are assigned to devices upon device provisioning and need to be used when registering those devices on TTS? And users are confused because this range isn't clearly stated in our docs?
=> doc: Note about JoinEUI range

doc/content/devices/troubleshooting/_index.md
=> doc: Troubleshooting packet collision

doc/content/reference/api/network_operations_center.md
=> doc: Add missing NOC API messages

doc/content/the-things-stack/cloud/billing-and-subscription-management/_index.md
=> doc: Subscription and billing mgmt FAQ update

doc/themes/the-things-stack/assets/css/common/global.scss
Fix css for badges.
This is the current state.
This is after the fix:
- Make badges align in a row instead of column.
=> Fix css for badges

doc/content/devices/troubleshooting/_index.md
=> doc: Document unable to access device err

doc/content/reference/configuration/the-things-stack.md
Remove old new-in-version tags
=> doc: Remove old new-in-version-tags

doc/content/the-things-stack/migrating/migration-tool/export-from-firefly.md
Document migration from Firefly. Refs https://github.com/TheThingsNetwork/lorawan-stack-migrate/issues/43.
This is waiting on external testing. I'll get back here when this is ready.
- Add firefly section.
=> Document migration from Firefly

doc/content/reference/api/authentication.md
In The Things Stack, to use the `OAuth access tokens` authentication method, it is important to register an OAuth client. The `redirect_uri` configuration is optional in the authorization request but at least one `redirect_uri` should be configured while registering the OAuth client.
Updated OAuth Client registration documentation:
Before:
After:
The sentence below is added to the registration steps in the OAuth Client registration guide. 
```
At least one redirect URI must be configured while registering the OAuth client.
```
Ref: https://www.thethingsindustries.com/docs/reference/api/authentication/#oauth-access-tokens
- Changes as per insights provided in the below GitHub issue:
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/996
=> doc: Update Redirect URI info to register an OAuth client

doc/content/devices/adding-devices/_index.md, doc/content/devices/adding-devices/adding-devices-in-bulk/_index.md, doc/content/devices/concepts/device-claiming/_index.md
Closes #1079 
Is this good place to locate these instructions? I find it a bit weird that it's separated from QR code-related docs and adding devices, but I somehow don't see these in Adding Devices. Also I'm curious, why does `join-server-enabled` option have to be set to false?
=> doc: Document claiming devices using claim auth code

doc/content/devices/adding-devices/adding-devices-in-bulk/_index.md
Fixes in-product documentation link.
The **Importing End Devices** doc link in the Console on `/console/applications/{application_id}/devices/import` is fixed this way.
The real fix is in the Console of course, but this is the quick workaround. Will file a PR for that as well.
=> Fix Console documentation link redirect

doc/content/reference/federated-auth/oidc/microsoft-entra.md
Update info about the Application (Client) ID in the [Microsoft Entra](https://www.thethingsindustries.com/docs/reference/federated-auth/oidc/microsoft-entra/) guide.
**Before:**
**After:**
- Add info about the Application (Client) ID for the client ID.
- Updated the `Secret ID` as Application (Client) ID in the [Registering the Provider in The Things Stack Section](https://www.thethingsindustries.com/docs/reference/federated-auth/oidc/microsoft-entra/#registering-the-provider-in-the-things-stack)
NA
=> doc: Add Application (Client) ID info in Microsoft Entra

doc/content/the-things-stack/interact/cli/configuring-cli/_index.md, doc/content/the-things-stack/interact/cli/installing-cli/_index.md, doc/content/the-things-stack/interact/cli/login/_index.md
Shortcodes in container tabs aren't resolving at the moment so these look broken
=> doc: Replace non-resolving Sandbox shortcode in tabs

doc/content/the-things-stack/interact/cli/troubleshooting/_index.md
=> doc: Troubleshoot using multiple boolean parameters in CLI cmd

doc/content/the-things-stack/management/telemetry/_index.md
In The Things Stack, metrics are exported only when a corresponding action occurs. Adding a note on exporting the metrics in the [telemetry](https://www.thethingsindustries.com/docs/the-things-stack/management/telemetry/) guide.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/1028#issuecomment-1946445488
**Before:**
**After:**
- Added a note point on exporting metrics.
...
=> doc: Add note on exporting metrics

doc/content/the-things-stack/interact/cli/troubleshooting/_index.md
Adding the error `error:cmd/ttn-lw-cli/commands:end_device_server_address_mismatch (Network/Application/Join Server address mismatch)` to the Troubleshooting CLI documentation.
https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1302
**New Section:**
- Added the Server Address mismatch error when using The Things Stack CLI.
...
=> doc: Add Server Address mismatch error when using TTS CLI

doc/content/integrations/webhooks/troubleshooting.md
Add the error unknown certificate authority with webhooks in the troubleshooting webhooks.
- Add error unknown certificate authority with the example event.
...
=> doc: Add error unknown certificate authority with webhooks

doc/content/integrations/cloud-integrations/thingsboard/_index.md
In the ThingsBoard Integration, the `Enable SSL` button is enabled by default for port 8883. To use port 1883, we need to disable the button.
**Before:** 
**After:** 
- Added point related to disabling the `Enable SSL` button while using `1883`. 
...
=> doc: Add the disabling of SSL button with 1883 port

doc/content/integrations/storage/enable.md
In the enable storage integration guide of `HTTP(REST)API` section, the FPORT is mentioned as `10`. Updated the storage integration default port as `100`.
Ref: https://www.thethingsindustries.com/docs/integrations/storage/enable/
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/1041#issuecomment-2034795043
NA
- Updated the default FPORT `100` for enabling the storage integration using APIs.
...
=> doc: Update default fport in enable storage integration API

doc/content/the-things-stack/migrating/migration-tool/troubleshooting/_index.md
Add migration tool troubleshooting section with the errors `error:pkg/redis:not_found (entity not found)` and `transport: error while dialing: dial tcp 52.212.223.226:8884: i/o timeout`.
- Added a troubleshooting migration tool section with the error and resolutions.
...
=> doc: Add migration tool troubleshooting section

doc/content/devices/configuring-devices/multicast/index.md
Add an example CLI command, including the flag `--mac-settings.ping-slot-periodicity <value>`, to register a sample Class B Multicast device to the multicast documentation guide. **Ref:** [Class B and Multicast](https://www.thethingsindustries.com/docs/devices/configuring-devices/multicast/#class-b-and-multicast)
**Before:**
**After:**
- Added an example CLI command for registering a Class B multicast device.
...
=> doc: Add CLI command to multicast doc

doc/content/the-things-stack/host/kubernetes/azure/upgrading/_index.md, doc/content/the-things-stack/host/kubernetes/generic/database-migrations/_index.md
References #1307 #1335
- Add `Upgrades` section to AKS docs.
- Update `Database Migrations` section of Generic k8s docs.
nil
=> Update Kubernetes deployments docs

doc/content/getting-started/best-practices/_index.md, doc/content/getting-started/faq/_index.md, doc/content/getting-started/next-steps/_index.md
Closes #1269 
If you think something else could be interesting here, it's open for suggestions
=> doc: Add general best practices

doc/content/the-things-stack/host/aws/ami/deployment-guide/_index.md
Add description for new param added in this [PR](https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/1173) for the AWS deployment template.
None
=> doc: Add description for new aws template param (TLSCertificateSecretARN)

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_list.md, doc/content/ttn-lw-cli/ttn-lw-cli_applications_webhooks_set.md, doc/content/ttn-lw-cli/ttn-lw-cli_gateways_list-frequency-plans.md, doc/content/whats-new/3.32.1.md, doc/data/api/ttn.lorawan.v3/messages/ApplicationWebhook.yml, doc/data/api/ttn.lorawan.v3/messages/ListFrequencyPlansRequest.yml, doc/data/api/ttn.lorawan.v3/messages/ParseGatewayQRCodeRequest.yml, doc/data/api/ttn.lorawan.v3/messages/ParseGatewayQRCodeResponse.yml, doc/data/api/ttn.lorawan.v3/services/EndDeviceRegistry.yml, doc/data/api/ttn.lorawan.v3/services/GatewayQRCodeGenerator.yml, doc/data/api/ttn.lorawan.v3/services/GatewayRegistry.yml
Release 3.32.1 documentation.
- Added documentation for 3.32.1.
```
```
```
```
=> Release 3.32.1 documentation

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/whats-new/3.32.2.md
Release 3.32.2 documentation.
- Added documentation for 3.32.2.
```
```
```
```
=> Release 3.32.2 documentation

doc/content/api/concepts/pagination/_index.md
Add note on limits. This is a one line change. No review necessary
NA
- Add note on limits
...
=> Add note on limits

doc/config/_default/config.toml, doc/content/the-things-stack/host/aws/ecs/changelog/index.md, doc/content/whats-new/3.32.3.md
Release 3.32.3 documentation.
- Added documentation for 3.32.3.
```
```
```
```
=> Release 3.32.3 documentation

doc/content/enterprise/kubernetes/generic/configuration/_index.md, doc/content/enterprise/kubernetes/generic/install-charts/_index.md, doc/content/enterprise/kubernetes/generic/prerequisites/_index.md, doc/content/enterprise/kubernetes/generic/prerequisites/sample-ingress-controllers.md, doc/content/enterprise/kubernetes/generic/troubleshooting/_index.md, doc/themes/the-things-stack/layouts/shortcodes/ttigpro.html
References issue [#44](https://github.com/TheThingsIndustries/lorawan-stack-k8s/pull/44) in lorawan-stack-k8s repo.
- Update step in prerequisites section of the k8s generic TTS hosting instructions.
- Update affected yaml configuration
- Is there more info need for the ingress controller step or is it enough?
=> doc: Update helm chart ingress controller setup info

doc/content/integrations/payload-formatters/javascript/uplink/_index.md
References [#7474 in thethingsnetwork/lorawan-stack](https://github.com/TheThingsNetwork/lorawan-stack/pull/7474).
- Add recvTime to decodeUplink() input in payload formatters section
- Update The Things Node example to include recvTime in the input
None.
=> Add recvTime to decodeUplink() input

.github/PULL_REQUEST_TEMPLATE.md
=> util: Fix CONTRIBUTING.md link in PR template

doc/content/integrations/data-formats/_index.md
References [#7451 in thethingsnetwork/lorawan-stack](https://github.com/TheThingsNetwork/lorawan-stack/pull/7451).
- Add attributes to uplink message data format
None.
=> doc: Add attributes to uplink message data format

doc/config/_default/config.toml, doc/content/enterprise/aws/ecs/changelog/index.md, doc/content/whats-new/3.33.2.md
Release 3.33.2 documentation.
- Added documentation for 3.33.2.
```
```
```
```
=> Release 3.33.2 documentation

doc/content/enterprise/aws/ami/deployment-guide/_index.md, doc/content/enterprise/aws/ami/post-deployment/_index.md, doc/content/enterprise/docker/certificates.md, doc/content/enterprise/docker/configuration/docker-compose-custom-certificates.yml, doc/content/enterprise/docker/configuration/docker-compose-enterprise.yml, doc/content/enterprise/docker/configuration/docker-compose-open-source.yml, doc/content/enterprise/docker/configuration/index.md, doc/content/enterprise/docker/configuration/ttn-lw-stack-docker-custom-certificates.yml, doc/content/enterprise/docker/configuration/ttn-lw-stack-docker-enterprise.yml, doc/content/enterprise/docker/configuration/ttn-lw-stack-docker-open-source.yml
Documentation for https://github.com/TheThingsIndustries/lorawan-stack/pull/4464 and https://github.com/TheThingsIndustries/lorawan-stack-aws/pull/1199.
- Document `ttgc` section for self-hosted
- Since one can use ACME certs for TTGC, also revised the TLS sections
- Document managed gateways for AWS AMI
- Also updated other parameters and defaults
This should not be merged before we merged the referenced PR and know which version this will land.
=> Document support for The Things Gateway Controller

doc/content/enterprise/aws/ecs/deployment/_index.md
Ref https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1385
Ref https://github.com/TheThingsIndustries/lorawan-stack-support/issues/1132
- Update TimescaleDB section.
- Add SQS queue section.
- Add TRM section.
nil
=> Add missing ECS docs

CONTRIBUTING.md, doc/content/concepts/advanced/user-management/_index.md, doc/content/concepts/advanced/user-management/rights/_index.md, doc/content/concepts/advanced/user-management/user/_index.md, doc/content/concepts/features/events/_index.md, doc/content/concepts/features/lorawan/fuota/_index.md, doc/content/enterprise/docker/_index.md, doc/content/enterprise/docker/configuration/index.md, doc/content/hardware/devices/adding-devices/adding-devices-in-bulk/_index.md, doc/content/integrations/adding-applications/_index.md, doc/content/integrations/payload-formatters/_index.md, doc/content/integrations/webhooks/creating-webhooks.md, doc/themes/the-things-stack/layouts/shortcodes/tabs/video.html
Closes #1404
- Add a new shortcode to embed iFrames into tabs.
- Update contributing guide.
=> Fix videos in tabs and add guide

doc/content/hardware/devices/adding-devices/manual/otaa/_index.md, doc/content/integrations/application-packages/using-the-api.md
Update the typos in the API call paths under [managing application packages](https://www.thethingsindustries.com/docs/integrations/application-packages/using-the-api/#listing-the-available-packages).
**New:**
- Updated the API path under [listing application packages](https://www.thethingsindustries.com/docs/integrations/application-packages/using-the-api/#listing-the-available-packages)
- Updated the API path under [creating associations](https://www.thethingsindustries.com/docs/integrations/application-packages/using-the-api/#creating-associations) for both application and end device
...
=> Update typos in API call paths for Managing Application Packages

doc/content/api/concepts/troubleshooting/_index.md
Ref: https://thethingsindustries.atlassian.net/browse/TTS-6571
Added new error `"neither_user_nor_organization" error`  heading in the [API troubleshooting guide](https://www.thethingsindustries.com/docs/api/concepts/troubleshooting/). 
As there is an explanation for a similar error, just added the error next to the existing error.
<details><summary>Error</summary>
<p>
```
{
    "code": 7,
    "message": "error:pkg/identityserver:neither_user_nor_organization (caller is neither a user nor an organization)",
    "details": [
        {
            "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
            "namespace": "pkg/identityserver",
            "name": "neither_user_nor_organization",
            "message_format": "caller is neither a user nor an organization",
          …
```
=> doc: Add new API error

doc/content/concepts/features/lorawan/adr/_index.md
There is no HTTP method in the example API call to configure the nbTrans [here](https://www.thethingsindustries.com/docs/concepts/features/lorawan/adr/#configure-nbtrans-for-an-end-device-per-data-rate)
**New:**
Added missing HTTP method `-X PUT` to configure nbTrans for an end device under [Configuring nbTrans](https://www.thethingsindustries.com/docs/concepts/features/lorawan/adr/#configure-nbtrans-for-an-end-device-per-data-rate)
...
=> doc: Add Missing HTTP method in nbTrans API

doc/content/hardware/gateways/models/thethingsindoorgatewaypro/_index.md
Add new error `gateway subscription not attached and active` while claiming The Things Indoor Gateway Pro. This is to add under new heading `Troubleshooting` in the [TTIGPro page](https://www.thethingsindustries.com/docs/hardware/gateways/models/thethingsindoorgatewaypro/)
<details><summary>Error Details</summary>
<p>
```
"error":"error:pkg/deviceclaimingserver:claim gateway (claim gateway)",
"error_cause":"error:unknown:unknown (gateway subscription not attached and active)",
```
</p>
</details> 
**New:**
Added new error `gateway subscription not attached and active` while claiming TTIGPro gateway and explanation.
...
=> doc: Add New error while claiming TTIGPro

doc/content/hardware/gateways/models/thethingsindoorgateway/_index.md
Update the typo in the CLI command used to claim the TTIG. There is a missing `\` in the command.
**New:**
Updated a missing `\`  in the command to claim the TTIG. 
...
=> doc: Update typo in TTIG claim command

doc/content/enterprise/kubernetes/generic/prerequisites/_index.md
A port mapping is wrong for the k8s Helm chart. This was in the configuration of Traefik and caused some trouble.
- ...
- ...
None.
=> doc: Update k8s ingress controller port mapping

doc/content/integrations/payload-formatters/javascript/uplink/_index.md
Long overdue documentation of the normalized payload schema.
References https://github.com/TheThingsNetwork/lorawan-stack/pull/7672
- Update the normalized payload schema description
=> Update normalized payload schema

doc/config/_default/config.toml, doc/content/enterprise/aws/ecs/changelog/index.md, doc/content/ttn-lw-cli/ttn-lw-cli_authentication-providers_create.md, doc/content/ttn-lw-cli/ttn-lw-cli_authentication-providers_get.md, doc/content/ttn-lw-cli/ttn-lw-cli_authentication-providers_list.md, doc/content/ttn-lw-cli/ttn-lw-cli_authentication-providers_update.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_list-bands.md, doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_list-phy-versions.md, doc/content/whats-new/3.34.2.md, doc/data/api/tti.lorawan.v3/messages/AuthenticationProvider.OIDC.yml, doc/data/api/tti.lorawan.v3/messages/Label.yml, doc/data/api/ttn.lorawan.v3/messages/BatchSetMACSettingsProfileRequest.yml, doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsRequest.yml, doc/data/api/ttn.lorawan.v3/messages/ListBandsRequest.yml, doc/data/api/ttn.lorawan.v3/services/NsEndDeviceBatchRegistry.yml
Release 3.34.2 documentation.
- Added documentation for 3.34.2.
```
```
```
```
=> Release 3.34.2 documentation
